### ISSUE TITLE
Add DNS and ICMP tunneling

### ISSUE THREAD

**Issue by steom** [erebe/wstunnel#10]
Consider to add DNS and ICMP tunneling

**Comment by erebe** [comment]
Hello,

You can already forward DNS requests with wstunnel, you have to start it in udp mode.

> wstunnel -u -L 53:your_remote_dns_server:53 wss://xxxxx

in your /etc/resolv.conf file juste replace the nameserver ip by 127.0.0.1, and dns requests will go trought the tunnnel.

For ICMP, I will not do it as it require to forge raw paquets which will require wstunnel to run as root (or equivalent capabilities)

**Comment by erebe** [comment]
Feel free to re-open if needed
