### ISSUE TITLE
hard to understand -L --localToRemote=[BIND:]PORT:HOST:PORT 

### ISSUE THREAD

**Issue by tlsalex** [erebe/wstunnel#102]
-L --localToRemote=[BIND:]PORT:HOST:PORT  Listen on local and forwards traffic from remote. Can be used multiple time

it's really hard to understand what does it mean , in the example of WireGuard udp tunnel  

wstunnel -v --udp --udpTimeoutSec -1 -L 127.0.0.1:51820:127.0.0.1:51820 wss://yourhost.tld/

wstunel will listen on 51820 , receive traffic from WireGuard interface , and send traffic through wss tunnel ? why it has two identical 127.0.0.1:51820 , it's really confuse me. it's "Listen on local and forwards traffic **from** remote" or "Listen on local and forwards traffic **to** remote" ; the last one 127.0.0.1:51820 is remote endpoint ?

**Comment by tlsalex** [comment]
Now I know how it work , it looks like it works like ssh -L option.
but I have another confusion

```
at server side:  wstunnel -v -s wss://0.0.0.0/ --restrictTo 127.0.0.1:51820
at client side:  wstunnel -v --udp --udpTimeoutSec -1 -L 127.0.0.1:51820:127.0.0.1:51820 wss://yourhost.tld/
```
at server side do we really need this  `--restrictTo 127.0.0.1:51820`  as at client side , whenever a connection is made to local 127.0.0.1:51820, the connection is forwarded over the secure channel, and a connection is made to 127.0.0.1:51820 from remote server

**Comment by erebe** [comment]
It is exactly as in ssh command, and as describe in the README.
If it is not clear enough, please create a PR to add more documentation in the README
