### ISSUE TITLE
feature request: content encryption

### ISSUE THREAD

**Issue by waclaw66** [erebe/wstunnel#105]
Could you please add possibility to encrypt websocket messages.
Reasoning is that content of messages can be compromised by e.g. corporate proxy which requires own certificate to decrypt https content.
It can be achieved for example by TLS certificate that can be also useful for user authentication.

**Comment by erebe** [comment]
Hello,
The point of wstunnel is not to protect the content of your traffic (like a VPN) it is merely to allow you to create a tunnel/network path across the firewall.
If you want to protect your data, you should look into using ssh -D or wireguard above wstunnel

**Comment by waclaw66** [comment]
I know, but both of ssh or VPN have some disadvantages, OpenSSH uses an unencrypted initial magic (packet analyzer recognizes it) and VPN needs virtual network adapter (not possible on corporate computers).
