### ISSUE TITLE
Confusion about ssh proxycommand

### ISSUE THREAD

**Issue by shadowrylander** [erebe/wstunnel#110]
Hello!

I'm a little confused about my particular situation, and was wondering if you could possibly point me in the right direction. I'm planning to use `wstunnel` to forward packets to `caddy`, using `wstunnel --server wss://0.0.0.0:443 -r 127.0.0.1:32443` and `wstunnel --server ws://0.0.0.0:80 -r 127.0.0.1:880`, where caddy will pick them up on ports `8443` and `880`, then forward them to the ssh daemon.

However, what proxycommand would I use on the client, as I am getting confused about the use of `localhost` here: `ssh -o ProxyCommand="wstunnel -L stdio:%h:%p ws://localhost:80" my-server`

Could you possibly tell show me what to use instead?

Thank you kindly for the help!

**Comment by erebe** [comment]
Hello,
you need to replace localhost:80 by the publix ip/domain name where your wstunnel server is listening. Replace tge port 80 by in your case either 8443 or 880

**Comment by shadowrylander** [comment]
Ah; so something like `ssh -o ProxyCommand="wstunnel -L stdio:%h:%p wss://remote:443" user@remote` and `ssh -o ProxyCommand="wstunnel -L stdio:%h:%p ws://remote:80" user@remote`?
