### ISSUE TITLE
openvpn no work help me

### ISSUE THREAD

**Issue by testingnic** [erebe/wstunnel#114]
I want to test this tunnel with openvpn but it was not successful, I would like to test it on TCP and UDP.

But I didn't have to exist, my Openvpn server is running on port 80, and local IP.

//SERVER
wstunnel --server wss://0.0.0.0:443 -r 127.0.0.1:80//OPENVPN

// CLIENT
wstunnel -L 9999:127.0.0.1:80 -p gogole.com:8080 wss://216.189.154.18:443

and in my openvpn client file local IP connection port 9999 and add the following:

route 216.189.154.18 255.255.255.255 net_gateway

but it doesn't work i have no success it works

**Comment by erebe** [comment]
Hello,
You can use `-p gogole.com:8080` option on the client. Google is not a proxy.
Please look at the readme, for complete examples
