### ISSUE TITLE
Reverse proxy with Nginx and SSL gives handshake error

### ISSUE THREAD

**Issue by arparthasarathi** [erebe/wstunnel#120]
Hello,

Thanks a lot for this helpful package. I am facing some difficulties in establishing a reverse proxy through Nginx and witnessing a TLS handshake error.

Nginx Config

```
server {
    server_name wstunnel.domain.tld www.wstunnel.domain.tld;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
    }

    listen 443 ssl;
    ssl_certificate /path/to/pem;
    ssl_certificate_key /path/to/privkey;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
server {
    if ($host = www.wstunnel.domain.tld) {
       return 301 https://$host$request_uri;
    }
    listen 80;
    server_name wstunnel.domain.tld www.wstunnel.domain.tld;
    return 404;
}
```

I tried running the `wstunnel` server in a couple of ways and both resulted in the following errors

#### Server command

`wstunnel -v --server ws://0.0.0.0:8080`  (changing 0.0.0.0 to 127.0.0.1 also doesn't help)

#### Error

```
Starting server with opts WsServerInfo {useTls = False, host = "0.0.0.0", port = 8080}
WAIT for connection on 0.0.0.0:8080
wstunnel: ParseException "string"
wstunnel: ParseException "string"
wstunnel: ParseException "string"
wstunnel: ParseException "string"
```

#### Server command

`wstunnel -v --server wss://0.0.0.0:8080`

#### Error

```
Starting server with opts WsServerInfo {useTls = True, host = "0.0.0.0", port = 8080}
WAIT for TLS connection on 0.0.0.0:8080
wstunnel: HandshakeFailed (Error_Packet_Parsing "Failed reading: invalid header type: 71\nFrom:\theader\n\n")
wstunnel: HandshakeFailed (Error_Packet_Parsing "Failed reading: invalid header type: 71\nFrom:\theader\n\n")
wstunnel: HandshakeFailed (Error_Packet_Parsing "Failed reading: invalid header type: 71\nFrom:\theader\n\n")
```

#### Client command used for both the above mentioned ways

```wstunnel -vD 8888 wss://wstunnel.domain.tld```

When I run the server without reverse proxying through nginx, the tunnelling works fine without any issues. But I am in need of Nginx for some basic auth and also the TLS implementation.

Any thoughts on this would be very helpful and appreciate it much! Thanks again.

**Comment by erebe** [comment]
Hello,

I don't have any issue with this setup running locally.

![image](https://user-images.githubusercontent.com/854278/190849688-ab3f3ef6-bc0d-460d-8bbe-5e815db861d7.png)

Try doing a tcpdump on the wstunnel server machine, to check the traffic you are receiving

**Comment by arparthasarathi** [comment]
@erebe Thanks much for getting back on this. On doing a tcp dump on the server, I get the following logs, but am not really sure if something is off. 

![Screenshot from 2022-09-19 12-56-09](https://user-images.githubusercontent.com/5359707/190968673-4142128b-a1a1-44a7-af20-ad68582652ef.png)

**Comment by erebe** [comment]
Hello,

I was talking more about taking a pcap in order to see the traffic with wireshark
https://www.wireshark.org/docs/wsug_html_chunked/AppToolstcpdump.html
https://www.howtoforge.com/capturing-packets-with-tcpdump-and-analyzing-with-wireshark/
