### ISSUE TITLE
Please update Docker Hub readme with a pointer to ghcr.io

### ISSUE THREAD

**Issue by dimaqq** [erebe/wstunnel#121]
I ended up following a merry chase of build script, actions ran (all outdated, no logs), github action definitions to figure out why the repo has updates from some months ago, while docker hub latest image is from 5 years ago.

**Comment by erebe** [comment]
Hello,

Sad to hear that you spent so much time on it, but I don't support docker images, the one on ghcr.io is only for my own usage.
I only support and maintain binary release, for everything else, it is up to you ;)
