### ISSUE TITLE
IPv6 over IPv4 w Wireguard

### ISSUE THREAD

**Issue by noelashford** [erebe/wstunnel#123]
Hello, I would like to use a WSTUNNEL Native IPv4 and route IPv6 across this. How would this work and can you provide documentation for this setup please? 

IE, I only have IPv4 but i want to enable a WG IPv6 Interface on both sides (no IPv4 at all WG wise) and route the IPv6 across the WSTUNNEL IPv4 Connection.... will it / nginx do the 6 to 4 conversion?  #Help :)

**Comment by noelashford** [comment]
IE, can this act as a 6to4 method itself. It attaches both sides on ipv6 but establishes over ipv4

**Comment by erebe** [comment]
Hello,

Honestly, I never tried, but wstunnel should do it automatically/without issues.
The ws client forward to ws server the dns name of what you want to connect to and it is the server that resolve this dns name.
So as long as the machine where the server is running is configured to use ipv6, it is going to work.

**Comment by noelashford** [comment]
Ok, I will try and report back, it should take me a few days. Let's keep this open in case there's unforseen issues.

**Comment by erebe** [comment]
re-open the issue if needed
