### ISSUE TITLE
Excuse me, does the WS tunnel support connection with the server through IPv6 domain name?

### ISSUE THREAD

**Issue by yzazzx2021** [erebe/wstunnel#124]
Because the ISP network uses the Qos speed limit method for UDP,The network to network tunnel of WireGuardTunnel, which is connected through IPv6 domain names, is very unstable,The ISP network package I use is a NAT4+dynamic IPv6 public network scheme, which can only be connected through the IPv6 domain name，So, does the WS tunnel support both ends to fill in IPv6 domain names for connection?
    thankyou

**Comment by erebe** [comment]
Hello,

There should be no issue if you use -D socks5 option.
for ipv6 domain name.

The -L option, static tunnel, support also ipv6 ip in the command line.

**Comment by yzazzx2021** [comment]
Then, if the network automatically replays and changes the address, can the WStunnel follow the change?

**Comment by erebe** [comment]
i am not sure to understand what you mean, but you can try by yourself, you will have the best answer
