### ISSUE TITLE
Any encryption?

### ISSUE THREAD

**Issue by vahidx4r4x** [erebe/wstunnel#126]
Hi.
Thanks for your hard work.
I have couple of questions.
Does wstunnel encrypt the connection by it self?
Does it anonymize the traffic?

**Comment by erebe** [comment]
Hello,

You need to use websocket over tls (wss) for wstunnel to encrypt the traffic. If you use normal webocket the data is just obfuscated (so it must bypass detection) but if someone captures traffic, it will not hard to de obfuscate.

For anonymization no, wstunnel does nothing for that by itself. But if you use wstunnel over tls (wss) you can change tls SNI if needed.
