### ISSUE TITLE
Could I get a 'musl' edition of the latest release for aarch-64?

### ISSUE THREAD

**Issue by blogmpw1** [erebe/wstunnel#128]
I tried, for a week as it for now. But im sorry, I just cant make it work. I cant fix the errors as below:

`~ $ ldd w
	libm.so.6 => not found
	libz.so.1 => not found
	libpthread.so.0 => not found
	librt.so.1 => not found
	libutil.so.1 => not found
	libdl.so.2 => not found
	libnuma.so.1 => not found
	libc.so.6 => not found
	ld-linux-aarch64.so.1 => not found`

Nor build it for myself. Can someone please send me one?
Sorry if it is not appropriate for asking help in this way.

**Comment by erebe** [comment]
Hello,

Can you share your build process steps ? Because with just this information, I can't help much.

Also, if your build machine is also the same target/machine the binary will run, you are not forced/obliged to build it statically.
Having library linked dynamically is ok.

**Comment by erebe** [comment]
Should be fixed now https://github.com/erebe/wstunnel/releases/download/v5.0/wstunnel-linux-aarch64.zip
