### ISSUE TITLE
Error: Data.Binary.Get.runGet at position 0: not enough bytes

### ISSUE THREAD

**Issue by tje3d** [erebe/wstunnel#129]
Hi, this error happens while i wanna do ssh through socks5:

```
wstunnel: Data.Binary.Get.runGet at position 0: not enough bytes
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:351:5 in binary-0.8.7.0:Data.Binary.Get
```

Command:

`ssh -o "ProxyCommand ncat --proxy 127.0.0.1:1080 %h %p" user@host`

same thing happens to telegram desktop and it fails to connect through the proxy

**Comment by tje3d** [comment]
might not related to wstunnel, closing

**Comment by dodid** [comment]
Seeing the same. Did you figure it out why?
