### ISSUE TITLE
Added statically-linked bin-file for openwrt-21.02

### ISSUE THREAD

**Issue by osnosn** [erebe/wstunnel#134]
The file "wstunnel-x64-linux" (v4.1) is statically linked and runs OK in openwrt.   
The file "wstunnel-aarch64-linux.zip" (v4.1) is dynamically linked and can NOT be run in openwrt.   
The file "wstunnel-aarch64-linux.zip" (v3.1) is statically linked and runs OK  in openwrt.   

----
Please add statically linked binary file for aarch64 (v4.1).    

```
rum command "ldd wstunnel-xxxx" , no required shared libraries.
run command "file wstunnel-xxxxx"
Required :   
  ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked,   
or   
  ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-aarch64.so.1,  
```

So it can run in OpenWRT-21.02. (x86-64 and armvirt).   

------
If you want to test by yourself, the following are the openwrt images (raw format) of the two architectures, which can be started and run in the KVM virtual machine.
If VMware is used, please convert the image format to vmdk.
If hyper-v is used, convert it to vhdx.
Use linux command "qemu-img" to convert image format. 
  for debian `apt install qemu-utils`, for centos `yum install qemu-img`.

[openwrt-22.03.2-armvirt-64-generic-ext4-combined-efi.img.gz](https://github.com/osnosn/3proxy-openwrt/releases/download/v0.9.3/openwrt-22.03.2-armvirt-64-generic-ext4-combined-efi.img.gz) (9MB).
[openwrt-21.02.5-x86-64-generic-ext4-combined-efi.img.gz](https://downloads.openwrt.org/releases/21.02.5/targets/x86/64/openwrt-21.02.5-x86-64-generic-ext4-combined-efi.img.gz) (9MB).

To enable wireguard in openwrt, only need `opkg install luci-app-wireguard`.

**Comment by erebe** [comment]
Indeed, I have some trouble to create static binary for aarch4 due to new version of GHC.
