### ISSUE TITLE
thread blocked indefinitely in an MVar operation

### ISSUE THREAD

**Issue by Arash-So** [erebe/wstunnel#135]
Every few hours I get this error on the client side and tunnel goes down until I run the command again.

`Client# /root/wstunnel-x64-linux -v -u --udpTimeoutSec 300 --websocketPingFrequencySec 10 -L 0.0.0.0:<port>:127.0.0.1:<port> wss://<ip>:<port>`

`Server# /root/wstunnel-x64-linux --server wss://0.0.0.0:<port> -r 127.0.0.1:<port>`

`Error on the client every few hours: wstunnel-x64-linux: thread blocked indefinitely in an MVar operation`

**Comment by sindy39** [comment]
I confirm this behaviour even without the `-v --udpTimeoutSec 300 --websocketPingFrequencySec 10` parameters and with forward-to address different from 127.0.0.1, and in both cases I've noticed so far, it took much less than an hour to happen.

**Comment by erebe** [comment]
Hello,

Thank you for reporting it. 
This issue with UDP is normally handled https://github.com/erebe/wstunnel/blob/master/src/Protocols.hs#L96 , as indeed as you mention @sindy39 this can happen when packets are dropped between client and server or the client UDP stream die.

I need to look why the catch is not handling the case anymore on latest version.
I will try to take the time during end of the month.

**Comment by rajaeem** [comment]
Hello,
The " wstunnel: thread blocked indefinitely in an MVar operation" also exists in the previous version 1.4.0.
[erebe](https://github.com/erebe)

**Comment by Arash-So** [comment]
Thank you **sindy39** and **erebe**. Right now I'm using Monit as a workaround to check on the client process every 5 seconds and re-start it, in case it exists with the error. It's been quiet okay and users usually don't feel the drop.

**Comment by erebe** [comment]
Hi back,

Can you use the binaries from this pre-release and let me know if you still encounter the issue 
https://github.com/erebe/wstunnel/releases/tag/v5.0

I manage to reproduce the issue and this should fix it, but would like your feedback before releasing it

**Comment by Arash-So** [comment]
Hi erebe, looks pretty stable and no issue so far. Thank you for the fix and great job!!
