### ISSUE TITLE
certificate verification

### ISSUE THREAD

**Issue by sindy39** [erebe/wstunnel#136]
Hello, in certain situations, even the fact that the tunneled payload is an encryption protocol should not be leaked. Could you please add also the possibility to specify a particular CA certificate file to use to verify the server certificate in client mode, to prevent MITM attacks from succeeding? I can see it is now possible to specify a certificate in server mode but the statically linked binary doesn't contain this feature yet.
Merci!

**Comment by erebe** [comment]
With new release, you can now provide your own tls certificate and key server side, and force check the tls connection client side.

Regarding pinning the certificate, thats a feature I will not add
