### ISSUE TITLE
 Rerout traffic

### ISSUE THREAD

**Issue by apktopsblog** [erebe/wstunnel#138]
Is it possible to Reroute traffic between 2 servers?

HTTP-client |   --> WS Server 1 --> WS Server 2 -->   | HTTP-server

**Comment by erebe** [comment]
Hello,

At the moment it is not possible to do it easily.
But you can run a 2nd client on WS server 1 that is going to re-forward to WS server 2

HTTP-client | --> WS Server [1] Ws client --> WS Server 2 --> | HTTP-server
