### ISSUE TITLE
Wireguard not working via this

### ISSUE THREAD

**Issue by Stevemoretz** [erebe/wstunnel#139]
Let me explain, I have a server with public ip of 23.95.191.205, the port 8080 on it is open can using the nc test I can connect to it via TCP without any issue and the connection is there.

My local wireguard port is 3334 and the remote wireguard port is 64731

On the server I used:

```bash
/usr/local/bin/wstunnel -v --server ws://0.0.0.0:8080 --restrictTo=127.0.0.1:64731
```

and for the client I used:

```bash
wstunnel -v --udp --udpTimeoutSec -1 -L 127.0.0.1:3334:127.0.0.1:64731 --upgradePathPrefix "wstunnel" ws://23.95.191.205:8080
```

In my wireguard I use 127.0.0.1:3334 as endpoint and the server ip is excluded to not have a loopback, MTU is a little bit less to allow the tunnel to be OK.

```conf
[Interface]
PrivateKey = 
Address = 10.66.66.2/32, fd42:42:42::2/128
DNS = 94.140.14.14, 94.140.15.15
MTU = 1000

[Peer]
PublicKey = 
PresharedKey = 
AllowedIPs = 0.0.0.0/4, 16.0.0.0/6, 20.0.0.0/7, 22.0.0.0/8, 23.0.0.0/10, 23.64.0.0/12, 23.80.0.0/13, 23.88.0.0/14, 23.92.0.0/15, 23.94.0.0/16, 23.95.0.0/17, 23.95.128.0/19, 23.95.160.0/20, 23.95.176.0/21, 23.95.184.0/22, 23.95.188.0/23, 23.95.190.0/24, 23.95.191.0/25, 23.95.191.128/26, 23.95.191.192/29, 23.95.191.200/30, 23.95.191.204/32, 23.95.191.206/31, 23.95.191.208/28, 23.95.191.224/27, 23.95.192.0/18, 23.96.0.0/11, 23.128.0.0/9, 24.0.0.0/5, 32.0.0.0/3, 64.0.0.0/2, 128.0.0.0/1, ::/0
Endpoint = 127.0.0.1:3334
```

When I turn on the wireguard I get this on client:

```
WAIT for datagrames on 127.0.0.1:3334
DEBUG :: Opening tcp connection to 23.95.191.205:8080
```

And nothing on the server, but I have no internet connection until I turn off the wireguard.

I also need to mention that I use udp2raw with wireguard and that works (so the wireguard config is fine) but this doesn't.

**Comment by erebe** [comment]
Hello,

I haven't checked all your allowed ip but are you sure that ip 23.95.191.205 of wstunnel server is not redirected to wireguard interface and creating a loop ?

Try to set a stztic route (ip route add...)  for this ip to your main interface

**Comment by Stevemoretz** [comment]
> Hello,
> 
> I haven't checked all your allowed ip but are you sure that ip 23.95.191.205 of wstunnel server is not redirected to wireguard interface and creating a loop ?
> 
> Try to set a stztic route (ip route add...) for this ip to your main interface

Thank you for answering yes I'm sure since I use the same wireguard client for udp2raw and it works via that:

server:

```bash
sudo /root/wg/udp2raw_x86 -s -l0.0.0.0:71 -r 127.0.0.1:64731 -k "passwd" --raw-mode icmp -a
```

```client
sudo /Volumes/HDD/Users/steve/Documents/scripts/udp2raw -c -l0.0.0.0:3334 -r23.95.191.205:71 -k passwd --raw-mode icmp
```

**Comment by Imfae** [comment]
Hello, I think the `::/0` at the end of your peer's AllowedIPs might be the problem. Its presence triggers wg's kill-switch and prevents wg traffic from tunneling through wstunnel.

**Comment by Stevemoretz** [comment]
Thanks to everyone, it was a actually an ip problem adding it statically solved the issue:

```bash
sudo route -n add -net 23.95.191.224/27 192.168.1.1 
```

By the way I used: https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/ for creating those allowedips
