### ISSUE TITLE
Origin SSL Certificate Error on CloudFlare

### ISSUE THREAD

**Issue by Stevemoretz** [erebe/wstunnel#141]
Hello, thank you for this amazing package.
I use tls mode to connect and that's what I need to get working.

server
```
/usr/local/bin/wstunnel -v --server wss://0.0.0.0:8443 --restrictTo=127.0.0.1:64731
```

client
```
wstunnel -v --udp --udpTimeoutSec -1 -L 127.0.0.1:3336:127.0.0.1:64731 --upgradePathPrefix "wstunnel" wss://104.21.0.249:8443  --hostHeader="example.com" --tlsSNI="example.com"
```

using the same commands with only changing wss to ws works, but that's not what I want.

using wss however on the client I get:

```
WAIT for datagrames on 127.0.0.1:3336
DEBUG :: Opening tcp connection to 104.21.0.248:8443
DEBUG :: Doing tls Handshake
DEBUG :: Opening Websocket stream
DEBUG :: Closing TLS
DEBUG :: Closing tcp connection to 104.21.0.249:8443
ERROR :: Cannot establish websocket connection with the server
DEBUG :: ====
MalformedResponse (ResponseHead {responseCode = 526, responseMessage = "Origin SSL Certificate Error", responseHeaders = [("Date","Tue, 20 Dec 2022 10:52:14 GMT"),("Content-Type","text/html"),("Transfer-Encoding","chunked"),("Connection","keep-alive"),("Cache-Control","no-store, no-cache"),("Report-To","{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=fDRoIOVWp4E3ngUbrL%2FhKzex74cFICyDKrxWWaUw2m0JF4vZ4djpSnjJqPFDNVMBCmCxOzSU1D89X%2B42vA8p%2FV%2BE1Zt47BIFoZNzet0vSa93nILF%2BtEomOtg22QT2QyD7HbtbW7RQg%3D%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}"),("NEL","{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}"),("Server","cloudflare"),("CF-RAY","77c7d3cfcb579061-FRA"),("alt-svc","h3=\":8443\"; ma=86400, h3-29=\":8443\"; ma=86400")]}) "Wrong response status or message."
====
DEBUG :: TIMEOUT connection
```

I already use SSL on cloudflare for other applications and it works (it is set to strict which means cloudflare doesn't have anything to do with the SSL itself and let's us use our own).

I believe this error occurs because your package uses self-sign certificate is there anyway to apply cert and key ourselves? So I can bypass this error?

**Comment by Stevemoretz** [comment]
Right now the workaround is to set ssl to full instead of full/strict in cloudflare which does so makes it work with self-sign-certificate and it worked.

**Comment by erebe** [comment]
Hello,

Yes you are right, the certificate by default of wstunnel is self-signed so it cannot pass cloudflare strict tls verification.

P.s: In progress release will allow you to set your own certificate for the server
