### ISSUE TITLE
Path with prefix not working

### ISSUE THREAD

**Issue by Stevemoretz** [erebe/wstunnel#142]
Hello, thank you again for this great package there sometimes it is necessary to have a websocket running on a path not the root

eg:

```
ws://80.25.12.16/transactions-realtime
```

I can connect to this using : 

```
wscat --connect ws://80.25.12.16/transactions-realtime/:80 --host example.com
```

And it works perfectly, yeah when I try using wstunnel it doesn't. 

------

let's say to run wireguard behind wstunnel.

So I will have on the server:

```
/usr/local/bin/wstunnel -v --server ws://0.0.0.0:80 --restrictTo=127.0.0.1:64731
```

On the client I have:

```
wstunnel -v --udp --udpTimeoutSec -1 -L 127.0.0.1:3337:127.0.0.1:64731 --upgradePathPrefix "wstunnel" ws://80.25.12.16/transactions-realtime/:80 --hostHeader="example.com" --tlsSNI="example.com"
```

I turn on the wireguard, and I get no logs on the server side of wstunnel if at the same time (While wireguard is on) I run:

```
wscat --connect ws://80.25.12.16/transactions-realtime/:80 --host example.com
```

I get a log:

```
Starting server with opts WsServerInfo {useTls = False, host = "0.0.0.0", port = 80}
WAIT for connection on 0.0.0.0:80
NEW incoming connection from 127.0.0.1:50076 [("X-Forwarded-For","92.22.74.26")]
Rejecting connection
```
Of course it rejects because I'm not supposed to do wscat there but at least I get a log, but for wstunnel client I get no log on the server and the wstunnel client also only gives these logs:

```
DEBUG :: Opening tcp connection to 80.25.12.16/transactions-realtime:80
DEBUG :: TIMEOUT connection
DEBUG :: DROP udp packet, client thread dead
```

Something must be wrong when using a path, I tried using `ws://80.25.12.16/transactions-realtime/:80` and `ws://80.25.12.16/transactions-realtime:80` but they both ask this way.

**Comment by erebe** [comment]
Hello,

wstunnel does not support putting an extra path on the server parameter `ws://80.25.12.16/transactions-realtime/:80` even it is accepted by the program.

To change the path, you need to use `--upgradePathPrefix "wstunnel"`, thats the only way to change the root path which is by default `wstunnel`

**Comment by Stevemoretz** [comment]
> Hello,
> 
> wstunnel does not support putting an extra path on the server parameter `ws://80.25.12.16/transactions-realtime/:80` even if it is accepted by the program.
> 
> To change the path, you need to use `--upgradePathPrefix "wstunnel"`, thats the only way to change the root path which is by default `wstunnel`
> 
> so your client should look like somthing
> 
> ```
> wstunnel -v --udp --udpTimeoutSec -1 -L 127.0.0.1:3337:127.0.0.1:64731 --upgradePathPrefix "transaction-realtime" ws://80.25.12.16:80 --hostHeader="example.com" --tlsSNI="example.com"
> ```

Thank you so much for this, actually I believe your solution should work in what I explained, however I have one extra proxy in the middle, and wstunnel is supposed to connect to that in my case and that middle proxy needs the path so my case won't work unless I find a way to run the middle proxy on root, thanks anyways really helpful had no idea what upgradePathPrefix does.
