### ISSUE TITLE
openvpn over wstunnel

### ISSUE THREAD

**Issue by VincentBehzad** [erebe/wstunnel#147]
Hello,
I have been working on this project to achieve OPENVPN connection over WSTUNNELv5.0 with TLS enabled without any reverse proxy (etc NGINX) to bypass censorship in environments with strict rules which rejects OVPN and accepts web traffic.

![Annotation 2023-01-17 201535](https://user-images.githubusercontent.com/121267634/212960007-6dd3209c-5849-4910-8200-d7c0eff06646.jpg)

**Server side Ubuntu 20.04**
I have openvpn daemon listening on :

> public_ip:1194

![Annotation 2023-01-17 192402](https://user-images.githubusercontent.com/121267634/212946266-d3a579c5-166e-4318-aa51-d97c4bf291be.jpg)

I executed wstunnelv5.0 using this code :

`./wstunnel --tlsCertificate=certificate.crt --tlsKey=private.key --restrictTo=public_ip:1194 --server wss://public_ip:443`

> Starting server with opts WsServerInfo {useTls = True, host = "public_ip", port = 443}
> WAIT for TLS connection on public_ip:443

checked `netstat` to see if wstunnel service is listening and it does.
p.s : firewall rules are allowed on this port.

**Client side Ubuntu 22.04 / Windows 10**
I executed wstunnelv5.0 using this code :
`./wstunnel --localToRemote=127.0.0.1:2020:127.0.0.1:1194 wss://remote_host_public_ip:443 --verbose `

> WAIT for tcp connection on 127.0.0.1:2020

with this code I am trying to connect my openvpn client through `local_host:2020` which I did bind it to `local_host:1194` then through wstunnel to `remote_host:443` which is listening on wstunnel agent on port 443.
`openvpn_client<====>127.0.0.1:2020<==Bind_to==>127.0.0.1:1194<==ws==>remote_host_public_ip:443<==Restrict_to==>public_ip:1194`

I even tried same concept on my home lab :
`./wstunnel --localToRemote=local_ip:2020:127.0.0.1:1194 wss://remote_host_public_ip:443 --verbose`

> WAIT for tcp connection on 0.0.0.0:2020 

on both situations I have encountered with this and was not able to connect to openvpn server.

- according to this log on client:

> DEBUG :: Opening tcp connection to remote_host_public_ip:443
DEBUG :: Doing tls Handshake   
DEBUG :: Opening Websocket stream
DEBUG :: Closing TLS  
DEBUG :: Closing tcp connection to remote_host_public_ip:443     
ERROR :: Cannot establish websocket connection with the server  
DEBUG :: ====  
MalformedResponse (ResponseHead {responseCode = 400, responseMessage = "Bad Request", responseHeaders = []}) "Wrong response status or message."
==== 
wstunnel: Network.Socket.accept: failed (Interrupted function call (WSAEINTR))   

- and this log on server:

> NEW incoming connection from client_ip:38705 []
Rejecting tunneling
NEW incoming connection from client_ip:6890 []
Rejecting tunneling

**when I remove `--restrictTo=public_ip:1194` from server side code and use `./wstunnel --tlsCertificate=certificate.crt --tlsKey=private.key --server wss://remote_host_public_ip:443`** 

I still cannot connect through wstunnel to OVPN server and I get different log but same issue.

- client side log:

> DEBUG :: Opening tcp connection to remote_host_public_ip:443 
DEBUG :: Doing tls Handshake  
DEBUG :: Opening Websocket stream 
CLOSE tunnel :: 127.0.0.1:2020 <==WSS==> remote_host_public_ip:443 <==TCP==> 127.0.0.1:1194 
DEBUG :: Closing Websocket stream 
DEBUG :: Closing TLS  
DEBUG :: Closing tcp connection to remote_host_public_ip:443 
DEBUG :: ====  
remote_host_public_ip:443: Network.Connection.connectionGetChunk: end of file 
====    
wstunnel: Network.Socket.accept: failed (Interrupted function call (WSAEINTR))  

- server side log:

> NEW incoming connection from client_ip:19001 []
CONNECTING to 127.0.0.1:1194
wstunnel: Network.Socket.connect: <socket: 17>: does not exist (Connection refused)

- [x] _my assumption is ovpn packets are being sent over wstunnel to remote host but they cannot be delivered to OVPN daemon and connection is closing according to this. How can I fix this issue?_

Thank you for your patience, I know it was a long writing, literally it took me +40minutes to write :-D

**Comment by erebe** [comment]
Hello,
Thank you for the effort and detailed explanation regarding your issue :)

Regarding case 1, where the server respond rejecting tunneling, it is due because on the client side the LocalToRemote right end does not match your restrict to. In your case as you put public_ip in restrict to, it should be also public_ip:1194 in local to remote right end instead of 127.0.0.1:1194

For case 2,  the server cannot connect to 127.0.0.1:1194, meaning nothing is listening on this address/port on your server. Check that your openvpn is really listening on 127.0.0.1 and not on some specific ip address (i. e: your public one). You can check that by doing `ss -lntp` to see on which ip/port is listening openvpn

**Comment by VincentBehzad** [comment]
Hello again,
First of all I would like to appreciate your time, fast response and exact information about the issue. 👍 

I was reading the documents about wstunnel and was thinking about Localto**Remote** and I discovered the same concept you are talking about.

- I did fix the issue with.

`./wstunnel --localToRemote=127.0.0.1:2020:daemon_listen_ip:1194 wss://remote_host_ip:443 --verbose`

One more thing, can I run udp over wstunnel? 
there is `-u` flag.

>  -u --udp     ===>     forward UDP traffic instead of TCP

- [ ] _does it mean I am actually running UDP over TCP without having UDP benefits (high speed connections)? or the connection is UDP on its purest form and over wstunnel ?_

**Comment by erebe** [comment]
Glad to hear it solved your issue.

For udp it is indeed udp over tcp and not just plain udp. (websocket is only over http/tcp)
udp => websocket over tcp => udp

openvpn can be configured to listen on tcp cnx, but if you chose to use udp (which is the default) be sure to lower your MTU (as described in the readme) to avoid slow speed.

**Comment by VincentBehzad** [comment]
That is awesome, Thank you again for your time and have a good day. 
keep up the good work :-D
