### ISSUE TITLE
Use multiple ports in one tunnel

### ISSUE THREAD

**Issue by Stevemoretz** [erebe/wstunnel#148]
I see that we can do this with this parameter from the client side

```
  -L --localToRemote=[BIND:]PORT:HOST:PORT      Listen on local and forwards
                                                traffic from remote. Can be
                                                used multiple time
```

But the `-r` option for the server doesn't indicate that we can use it multiple times.

```
  -r --restrictTo=HOST:PORT                     Accept traffic to be
                                                forwarded only to this service
```

Is that just missing from `-r` parameter's documentation or is that not possible yet?

Also could be nice if we could use a range map like from client's port `6000 to 7000` to server's port `6000 to 7000` right now for doing that we need to add 1000 `-L` params.

**Comment by erebe** [comment]
Hello,
sadly, this is not possible at the moment ;(

**Comment by Stevemoretz** [comment]
> Hello, sadly, this is not possible at the moment ;(

Hello thank you so much for responding :) so we can use multiple `-l`s without any `-r` s for now.
Still is great thank you :0
