### ISSUE TITLE
[Question] How to use this tool to tunnel ws ssh ?

### ISSUE THREAD

**Issue by chromer030** [erebe/wstunnel#149]
Hi , thanks for this project , how we can use this tool to SSH Tunneling using a reverse proxy technique (SSH WS) ?
(is there any command like `ssh -N -D 1080 -p 22 user@server` ?)

For using the services like SSHMAX :

````
Server | : de-ws.sshmax.xyz
Username | : sshmax-test2
Password | : test2
Created | : 19 Jan 2023
Expired | : 26 Jan 2023
Protocol | : Websocket
Port | : 80, 2082
Port SSL/TLS | : 443, 2083
UDPGW | : 7200, 7300
Payload HTTP : GET / HTTP/1.1[crlf]Host: de-ws.sshmax.xyz[crlf]Upgrade: websocket[crlf][crlf]
Payload SSL : GET wss://SNI_bug_host/ HTTP/1.1[crlf]Host: de-ws.sshmax.xyz[crlf]Upgrade: Websocket[crlf]Connection: Keep-Alive[crlf][crlf]
````

**Comment by erebe** [comment]
Hello,

Reverse tunneling in not implemented.
The only solution available at the moment is to create a tunnel that target your ssh server and after use ssh to do the reverse tunneling.

I.e: 
wstunnel -L 2222:127.0.0.1:22 ws//my_remote_server

and after that use ssh

ssh -p 2222 -R xxxx user@localhost

**Comment by chromer030** [comment]
Tried with 5.1 and got segmentation fault :

```
$ ./wstunnel -L 2222:127.0.0.1:22  ws://sshmax-user@194.233.81.125
WAIT for tcp connection on 127.0.0.1:2222
[1]    28756 segmentation fault (core dumped)  ./wstunnel -L 2222:127.0.0.1:22 ws://sshmax-user@194.233.81.125

```

**Comment by erebe** [comment]
Please use 5.0, the release for the 5.1 is not yet done, I haven't made a static binary for the 5.1

**Comment by ghogarerama26-netizen** [comment]
Vivi
