### ISSUE TITLE
android client

### ISSUE THREAD

**Issue by mghadam** [erebe/wstunnel#15]
Any ideas on how to run wstunnel client on android ?

**Comment by erebe** [comment]
You can try the arm version of the previous release https://github.com/erebe/wstunnel/releases/download/1.2/wstunnel-armhf , it should work if it is the same architecture.

**Comment by zhmylove** [comment]
Can we somehow help you in cross-compilation it for arm? The previous release works good but doesn't have "update path" option thus we can't hide a tunnel behind a real website (which is vital for our purposes).

**Comment by erebe** [comment]
Havue you checked the last release https://github.com/erebe/wstunnel/releases/tag/2.0, there is a build for ARM.
If I haven't messed up it should contain the lastest patches.

Let me know if it is not the case
