### ISSUE TITLE
[Question] wstunnel vs stunnel

### ISSUE THREAD

**Issue by nikkymen** [erebe/wstunnel#152]
Thank you for your work!

Question: what are the advantages of _wstunnel_ over the good old _stunnel_ (stunnel.org)?
As far as I understand, _stunnel_ solves the same problem as _wstunnel_.

I apologize if the question sounds silly, as I am not an expert in this field.

**Comment by erebe** [comment]
can't tell you precisely as i never used it.
But from the landing page, it just add tls on top on existing tcp cnx. 
Wstunnel is wrapping your existing cnx over websocket + tls if enabled. So there is 2 layer
