### ISSUE TITLE
Performance tunning 

### ISSUE THREAD

**Issue by downright-ux** [erebe/wstunnel#158]
Hi,
I was wondering if there is anyway to performance tune the tunnel at all.
I noticed when running a test that the download speed drops by half. 
I noticed though the upload speed doubles.

Running with Wireguard 

here is the configuration setup

Wireguard
```
[Interface]
PrivateKey = xxxxxxxxxxxxxxxxxxxxxxx=
Address = 172.20.8.16/32,fd20:d69:146e:9003:cafe:16::/128
DNS = 127.0.0.1
MTU = 1320
PreUp = systemctl start wstunnel.service
PreDown = systemctl stop wstunnel.service

[Peer]
PublicKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
PresharedKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
AllowedIPs = 172.20.8.0/24,10.172.0.0/20,10.172.16.0/24,fd20:d69:146e:9003:0:0:0:0/64,2600:1900:4160:11d3::/64
Endpoint = 127.0.0.1:51820
```

wstunnel config

```
[Unit]
Description=Tunnel WireGuard UDP over websocket
After=network.target

[Service]
Type=simple
User=nobody
ExecStart=/usr/local/bin/wstunnel -v --udp --udpTimeoutSec -1 -L 127.0.0.1:51820:127.0.0.1:51820 wss://xx.xx.xx.xx:443 
Restart=no

[Install]
WantedBy=multi-user.target
```

Without wstunnel running
81.0 Mbps Down 
45.7 Mbps Up 
170 Ping
0.6 Jitter

With wstunnel running
 41.5 Mbps Down
 83.0 Mbps Up
 168 Ping
 0.6 Jitter

**Comment by erebe** [comment]
Maybe you don't have a symmetrical bandwith (which is common with consumer ISP) so the overhead of sending more data, reduce your down stream.

For the overhead of wstunnel, there is not much to do sadly. that's tge issue of encapsulating twice
