### ISSUE TITLE
gets discconected

### ISSUE THREAD

**Issue by Real-kia** [erebe/wstunnel#159]
I use wstunel to tunnel between 2 vps and the on second vps I am running v2ray and using this tunnel to create a vpn connection.
I also tunnel to a domain that has cloudflare proxy and points to my second vps.
The problem is that sometimes it gets disconnected ( it takes 1 minute to recconect) and it's not just for me some other people that use other vps have also this problem.

**Comment by erebe** [comment]
Please use the bug report template
