### ISSUE TITLE
Dump request

### ISSUE THREAD

**Issue by malikshi** [erebe/wstunnel#16]
Any update will be added SNI?? I know it's already support tls but it's might be better add SNI for bypassing if blocked by firewall

**Comment by erebe** [comment]
Hello,
Can you describe a bit more what you mean or point toward some resources because I don't understand what you are asking.
For me SNI is the hostname that is passed in the TLS header.

**Comment by erebe** [comment]
Hello,
Regarding adding raw tls as a transport protocol, I will not do it

**Comment by malikshi** [comment]
> Hello,
> 
> Thanks for letting me know of gost, I wasn't aware of such project, seems very handy.
> Regarding adding raw tls as a transport protocol, I will not do it as the main goal of the wstunnel is just to use websocket transport protocol.
> Regarding obfuscating the SNI in the TLS header, I will check if I can do it, but I think it is a too low level feature for the lib I use.
> 
> I will let you know the outcome

thanks a lot sir
