### ISSUE TITLE
--localToRemote should resolve name of HOST remotely, not locally

### ISSUE THREAD

**Issue by HenriWahl** [erebe/wstunnel#162]
**Is your feature request related to a problem? Please describe.**
Maybe I did something wrong but I did achieved to use the localToRemote feature when using a hostname as HOST which is known where I call this.

**Describe the solution you'd like**
It would be nice if the value for HOST could be some hostname which exists in the remote network internally.

**Describe alternatives you've considered**
I found a solution using _localhost_ as hostname but this makes things more complicated.

**Comment by erebe** [comment]
Can you give me the command line you are using ?
Because the host from --localToRemote is already resolved by wstunnel server and not on the client.

**Comment by HenriWahl** [comment]
Hi @erebe,
thanks for your quick reply. 
I tried to repoduce my problem but now I only found it working as you described it. This way it makes absolutely sence and I am not able to find out what went wrong.

So don't mind this "issue" and thanks for a great app!
