### ISSUE TITLE
ERROR: /etc/wireguard/wstunnel.sh: line 119: dig: command not found

### ISSUE THREAD

**Issue by pahlse** [erebe/wstunnel#164]
**Describe the bug**
```
[#] source /etc/wireguard/wstunnel.sh && pre_up myvpn
/etc/wireguard/wstunnel.sh: line 119: dig: command not found
[#] ip link delete dev myvpn
Cannot find device "myvpn"
```

**To Reproduce**
- Set up Wireguard on vps and client
- Set up wstunnel on vps and client

I get the above error when I run `$ sudo wg-quick up myvpn` on my archlinux machine. Any ideas what's going wrong?

**Desktop (please complete the following information):**
 - OS:  Arch Linux x86_64
 - Browser. Brave
 - Version 6.4.12-arch1-1

**Additional context**
Wireguard works fine without wstunnel.

**Comment by erebe** [comment]
Hello,
Your issue is not related to wstunnel. 
Don't know were you got your script, but you are missing the dig command line tool. (look into your distro how to install it)
