### ISSUE TITLE
Build instructions for macOS on Apple Silicon M1/M2 (aarch64/arm64)

### ISSUE THREAD

**Issue by struanb** [erebe/wstunnel#165]
**Describe the bug**

The instructions given to install the stack tool with `curl -sSL https://get.haskellstack.org/ | sh` do not work, because according to https://docs.haskellstack.org/en/stable/install_and_upgrade/:

> The Stack repository uses GitHub-hosted runners to create binary distributions for macOS. GitHub-hosted runners are not expected to be available for macOS on Apple silicon until July to September 2023.
> 
> Consequently, for Mac computers with Apple silicon, the easiest way to install Stack directly (rather than use GHCup) is to obtain the 'unofficial' osx-aarch64 binary distribution released by the GHCup developers and copy it to a location on the PATH. *.tar.gz archive files containing those binary distributions are available at the directories here: https://downloads.haskell.org/ghcup/unofficial-bindists/stack/.
> 

**Expected behavior**

Specify the Apple Silicon M1/M2 (aarch64/arm64) build case, by explaining that until upstream Haskell supports this archiecture, the `stack` binary must be installed via the link above.

Also, specify that you must run:

```
stack init --force # Rewrites stack.yaml to use ghc-9.4.6 rather than ghc-9.02 (which won't compile)
stack setup
stack install
```

This builds a dynamically-linked aarch64 binary. On MacOS it's not possible to build a statically-linked binary by appending `ld-options: -static` to `wstunnel.cabal`.

Please let me know if you'd like me to submit a pull request containing these `README.md` changes and if I can contribute my MacOS aarch64 `wstunnel` v5.1 build to the Releases page.

**Comment by erebe** [comment]
Hello,

Sure feel free to open a PR to change that, and if you have a binary for V6.0, I will put it in the release section.


Thanks :)

**Comment by struanb** [comment]
[wstunnel.zip](https://github.com/erebe/wstunnel/files/12713630/wstunnel.zip)

Here is a wstunnel v6.0 binary compiled on arm64/aarch64 Mac OS Ventura 13.5.2 using the above steps.

**Comment by erebe** [comment]
Added it, thanks :)
