### ISSUE TITLE
wstunnel: failed to create OS thread: No error information

### ISSUE THREAD

**Issue by Terramoto** [erebe/wstunnel#167]
I'm running the file on a CPanel server running almalinux 8, i'm assuming this error is a limitation of the hosting account where i'm running it from. Is it possible to run it on a single thread or specify max-threads?

Server:
`.\wstunnel.exe --server ws://0.0.0.0:8080`
Client:
`.\wstunnel.exe -D 8888 ws://server-ip:8080`

Log:
```NEW incoming connection from :56755 []
NEW incoming connection from :56752 []
NEW incoming connection from :56753 []
wstunnel: failed to create OS thread: No error information```

**Comment by erebe** [comment]
You can use the +RTS option to request only 1 thread.

I.e: `wstunnel +RTS -N1 -RTS` use `wstunnel +RTS -help -RTS` for a complete list of option
