### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by tobiasBora** [erebe/wstunnel#17]
Hello,

First thanks for this very interesting software. I'm trying to package it for the great pure package manager [nix](https://nixos.org/nix/), but I have a compilation error: after running `cabal2nix . > wstunnel.nix`, that generated the following file:

```
{ mkDerivation, async, base, base64-bytestring, binary, bytestring
, classy-prelude, cmdargs, connection, hslogger, mtl, network
, network-conduit-tls, stdenv, streaming-commons, text
, unordered-containers, websockets
}:
mkDerivation {
  pname = "wstunnel";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    async base base64-bytestring binary bytestring classy-prelude
    connection hslogger mtl network network-conduit-tls
    streaming-commons text unordered-containers websockets
  ];
  executableHaskellDepends = [
    base bytestring classy-prelude cmdargs hslogger text
  ];
  testHaskellDepends = [ base text ];
  homepage = "https://github.com/githubuser/wstunnel#readme";
  description = "Initial project template from stack";
  license = stdenv.lib.licenses.bsd3;
}
```
I put in `default.nix` the code:
```
{ nixpkgs ? import <nixpkgs> {}, compiler ? "ghc863" }:
nixpkgs.pkgs.haskell.packages.${compiler}.callPackage ./wstunnel.nix { }
```
and to compile I ran `nix-build default.nix`. This downloads all the dependencies, however when it comes to compilation, the 3rd file "src/Types.hs" fails to compile:
```
Preprocessing library for wstunnel-0.1.0.0..
Building library for wstunnel-0.1.0.0..
[1 of 7] Compiling Credentials      ( src/Credentials.hs, dist/build/Credentials.o )
[2 of 7] Compiling Logger           ( src/Logger.hs, dist/build/Logger.o )
[3 of 7] Compiling Socks5           ( src/Socks5.hs, dist/build/Socks5.o )
[4 of 7] Compiling Types            ( src/Types.hs, dist/build/Types.o )

src/Types.hs:22:1: error:
    • Can't make a derived instance of ‘Generic PortNumber’:
        The data constructors of ‘PortNumber’ are not all in scope
          so you cannot derive an instance for it
    • In the stand-alone deriving instance for ‘Generic PortNumber’
   |
22 | deriving instance Generic PortNumber
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
builder for '/nix/store/dp76w5kgmypi9n4fj9smlgd7zf5px3z3-wstunnel-0.1.0.0.drv' failed with exit code 1
error: build of '/nix/store/dp76w5kgmypi9n4fj9smlgd7zf5px3z3-wstunnel-0.1.0.0.drv' failed
```
Any idea why? (note: with stack init && stack build it works)

**Comment by erebe** [comment]
Can you try with GHC 8.0.2 instead of 8.6.3 ?

PortNumber constructor is correctly imported in Types.hs, so I don't know why GHC complains in this case :x

**Comment by tobiasBora** [comment]
Unfortunately NixOs does not have such old GHC version available... so not sure how to do that. :-\

**Comment by tobiasBora** [comment]
Ok, it appears that the Network package changed a bit, so it's not possible to derive Generic automatically, but it's not a problem as it's still possible to implement Hashable from the numerous value of PortNumber. See my pull request (tested on both nix and stack) [here](https://github.com/erebe/wstunnel/pull/18).

**Comment by erebe** [comment]
Ha sorry, I can't upgrade to the latest LTS due to this issue #8
I need to make some changes in order for wstunnel to work with the latest tls package.

Sadly I don't have much free time right now, so it may take time before I upgrade it.

Can you try and let me know if you reproduce the issue #8 with your version, or if everything is working fine ?

**Comment by erebe** [comment]
it works now with the latest version of ghc (8.6.5)
