### ISSUE TITLE
Does the latest version support reverse connections?

### ISSUE THREAD

**Issue by worm001** [erebe/wstunnel#170]
As the question goes, I have a service on port 3333 on the intranet. How should I set up the client to access it on a server with a public network?

**Comment by erebe** [comment]
Hello,

Not yet, for now the only solution is to run `ssh -R ...` inside the tunnel to have a remote connection. 

You can take a look at this issue for information https://github.com/erebe/wstunnel/issues/84

**Comment by erebe** [comment]
Hello,

Version 8 now support reverse tunneling https://github.com/erebe/wstunnel/releases/tag/v8.0.0
