### ISSUE TITLE
android support bin

### ISSUE THREAD

**Issue by testingnic** [erebe/wstunnel#180]
Can you make it support openvpn and also make binaries for android? Is it possible?

**Comment by erebe** [comment]
Hello,

It should already be possible to use openvpn with wstunnel. You can follow the same doc as WireGuard I guess.
For the android binary, I am going to try.

**Comment by testingnic** [comment]
android binary is good option

**Comment by erebe** [comment]
Sadly,
Cross compilation for android build is stuck by https://github.com/cross-rs/cross/issues/1222 . In next release it should be possible.

Would you mind trying https://github.com/erebe/wstunnel/releases/download/v7.9.1/wstunnel_7.9.1_linux_arm64.tar.gz and let me know it if works on Android ?

**Comment by testingnic** [comment]
tranks bro,  work
