### ISSUE TITLE
does not support passwords with special characters when using HTTP proxy

### ISSUE THREAD

**Issue by keke1229488344** [erebe/wstunnel#183]
My httpproxy password contains the special character `@`. (e.g. username=user, passwd=pass@123)
Unfortunately when I use `./wstunnel client -L tcp://127.0.0.1:9999:127.0.0.1:6666 -p http://user:pass@123@httpproxy:8080 wss://server:443` command, it doesn't work!

**Comment by yu-james** [comment]
I would say try URL encoding first: pass%40123

**Comment by keke1229488344** [comment]
> I would say try URL encoding first: pass%40123

yep... thanks, but have try it (`%40` and `0x40`), still not work : (

but now I using cntlm to convert the httpproxy to no-special-character httpproxy, it works.

**Comment by erebe** [comment]
It should be fixed with https://github.com/erebe/wstunnel/releases/tag/v7.9.2
Can you let me know it is ok ?

**Comment by erebe** [comment]
Hello,
it should be fixed with https://github.com/erebe/wstunnel/releases/tag/v7.9.2
Would you mind trying and letting me know ?

**Comment by keke1229488344** [comment]
coool, thanks a lot, v7.9.2 now working well using `%40` to instead of `@`.

Here is a table of special character correspondences that should be correct to help those in need:

```
!   #   $    &   '   (   )   *   +   ,   /   :   ;   =   ?   @   [   ]
%21 %23 %24 %26 %27 %28 %29 %2A %2B %2C %2F %3A %3B %3D %3F %40 %5B %5D
```
