### ISSUE TITLE
Do you support a 32-bit Windows version?

### ISSUE THREAD

**Issue by kanran111** [erebe/wstunnel#185]
Some computers in our company use 32-bit Windows, so they can't run it. It would be great if you could support 32-bit Windows. Thanks you.

**Comment by erebe** [comment]
Hello,
It should be possible, i will try when i get back end of november.

**Comment by erebe** [comment]
Would you mind trying the pre-release https://github.com/erebe/wstunnel/releases/tag/v7.9.4 , the archive  wstunnel_7.9.4_windows_386.tar.gz  and let me know if it is ok for you ?

P.s: Out of curiosity, what kind of company are you working in to still have 32bits computers ?
