### ISSUE TITLE
rustup: unrecognized OS type: OpenBSD

### ISSUE THREAD

**Issue by lucdig** [erebe/wstunnel#186]
Is it possible to add OpenBSD support?

Thanks

**Comment by erebe** [comment]
Hello,

I don't think I will maintain a build for openbsd, as it is a tier 3 arch, meaning best effort, architecture for Rust.
But if you install rustc & cargo directly from your package manager (without using rustup) on openbsd, and do a `cargo build --release` it should work.

Let me know if you have build issue
