### ISSUE TITLE
"Phone Home" Style connections?

### ISSUE THREAD

**Issue by JustinGrote** [erebe/wstunnel#19]
Does this project support "phone home" connections like:
https://github.com/rightscale/wstunnel

Basically, a "probe" device connects to a "server" out on the internet and establishes a persistent websocket, then other "clients" can connect to the server and ride the connection back in to access an internal tcp port.

Our use case for this is management systems that we have at customer client sites as an MSP that we'd like to SSH and RDP to other devices but without having to set up IPSec connectiviy. We do this with SSH tunneling today but websockets would be more "transparent" to firewalls.

Thanks.

**Comment by erebe** [comment]
Hello,

That's reverse tunneling and it is not implemented in wstunnel, that's still in todo.
But you can do it anyway if you have ssh installed on the server.

rdp <==> client <==> server <==> you


1. On the client machine do `wstunnel -L 1212:localhost:22 xxx`, this will open a websocket tunnel on the client machine that will forward traffic on the ssh daemon.
2. Still on the client side do a `ssh -R 2020:rdp_machine:rdp_port localhost:1212` this will create a reverse tunnel using ssh and the websocket tunneling, that will forward traffic from the server on port 2020 toward the rdp machine
3. On your side, do either a `ssh -L 2020:localhost:2020 server` if you have direct access to the server side, or use wstunnel. That will create a tunnel on your machine that will forward traffic to the server on port 2020 (so using our reverse tunnel)
4. Do a rdp localhost:2020 to use the tunnel

Enjoy
