### ISSUE TITLE
STDIO for Windows

### ISSUE THREAD

**Issue by bluewalk** [erebe/wstunnel#193]
**Is your feature request related to a problem? Please describe.**
When trying to use stdio with ssh on windows the main thread panicks shouting `stdio is not implemented for non unix platform`.
I am quite sure the non-rust version did support Windows stdio.

**Describe the solution you'd like**
Have stdio support available for when using wstunnel on Windows

**Describe alternatives you've considered**
Of course you can run the command separately and use tcp:// and connect to localhost.

**Comment by erebe** [comment]
Hello,

Indeed, I will try to add a custom implementation for non unix system in the coming days.

**Comment by erebe** [comment]
Would you mind trying this release and letting me know if it works for you ?
https://github.com/erebe/wstunnel/releases/download/SO_MARK/wstunnel-x86_64-pc-windows-msvc.zip

**Comment by erebe** [comment]
It is released in https://github.com/erebe/wstunnel/releases/tag/v8.3.0 enjoy :)
