### ISSUE TITLE
Compile error in Docker Container.

### ISSUE THREAD

**Issue by etanchev** [erebe/wstunnel#194]
I receive the bellow error when i try to compile it in docker container . I dont have problem when i compile it on raspberrypi (Buster) inside docker coniner.

Caused by:
  process didn't exit successfully: `/usr/local/rustup/toolchains/1.73.0-x86_64-unknown-linux-gnu/bin/rustc --crate-name wstunnel --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=211 --crate-type bin --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto=fat -C codegen-units=1 -C debuginfo=1 -C metadata=de9dd86c18f3e15e -C extra-filename=-de9dd86c18f3e15e --out-dir /build/target/release/deps -L dependency=/build/target/release/deps --extern ahash=/build/target/release/deps/libahash-5d06c206991f88e9.rlib --extern anyhow=/build/target/release/deps/libanyhow-6dd1bdbfaccbc611.rlib --extern async_trait=/build/target/release/deps/libasync_trait-02b5cf80b2d8e2ad.so --extern base64=/build/target/release/deps/libbase64-7a802bc7b9758d60.rlib --extern bb8=/build/target/release/deps/libbb8-fb5467fffeb639d9.rlib --extern bytes=/build/target/release/deps/libbytes-52e31a3cc3d5def0.rlib --extern clap=/build/target/release/deps/libclap-995665dc11031e54.rlib --extern fast_socks5=/build/target/release/deps/libfast_socks5-918fc086f705cf22.rlib --extern fastwebsockets=/build/target/release/deps/libfastwebsockets-16676d80703c1151.rlib --extern futures_util=/build/target/release/deps/libfutures_util-26577b494caf77f4.rlib --extern hyper=/build/target/release/deps/libhyper-72888548af189b11.rlib --extern jsonwebtoken=/build/target/release/deps/libjsonwebtoken-e71f35a52a755b2c.rlib --extern log=/build/target/release/deps/liblog-8f7a843cd719b684.rlib --extern nix=/build/target/release/deps/libnix-706889720ef5e66d.rlib --extern once_cell=/build/target/release/deps/libonce_cell-9dc1720f87b350cf.rlib --extern parking_lot=/build/target/release/deps/libparking_lot-d575adbf0b8b88b1.rlib --extern pin_project=/build/target/release/deps/libpin_project-b2aa614d228e72eb.rlib --extern rustls_native_certs=/build/target/release/deps/librustls_native_certs-0ad625ec7fcaa367.rlib --extern rustls_pemfile=/build/target/release/deps/librustls_pemfile-954cc28189f1050a.rlib --extern scopeguard=/build/target/release/deps/libscopeguard-c03dd72933690824.rlib --extern serde=/build/target/release/deps/libserde-033991a222f0094f.rlib --extern socket2=/build/target/release/deps/libsocket2-b389d5c9b40c127e.rlib --extern tokio=/build/target/release/deps/libtokio-3427cb7fced15241.rlib --extern tokio_fd=/build/target/release/deps/libtokio_fd-0814e84db169440d.rlib --extern tokio_rustls=/build/target/release/deps/libtokio_rustls-1105053972c54139.rlib --extern tokio_stream=/build/target/release/deps/libtokio_stream-a300f4b0cafa6356.rlib --extern tracing=/build/target/release/deps/libtracing-92e5447286a2bec9.rlib --extern tracing_subscriber=/build/target/release/deps/libtracing_subscriber-f013a470d358bd4e.rlib --extern url=/build/target/release/deps/liburl-7abdab22c41e085c.rlib --extern urlencoding=/build/target/release/deps/liburlencoding-8e06294a8719e494.rlib --extern uuid=/build/target/release/deps/libuuid-f54d64b582f3c576.rlib --cfg uuid_unstable -L native=/build/target/release/build/ring-32f2ec65ed2c4ab0/out` (signal: 9, SIGKILL: kill)

**Comment by erebe** [comment]
It got `(signal: 9, SIGKILL: kill)`, so most likely the build took too much RAM and got killed by your OS.
* Try freeing some memory before launching the build.
* Try adding `-j 1` to cargo build

**Comment by etanchev** [comment]
That solve the problem thank you.
