### ISSUE TITLE
Apple Silicon builds

### ISSUE THREAD

**Issue by vercas** [erebe/wstunnel#199]
Older versions used to come with macOS ARM builds, new versions don't.  
Is there anything blocking these?  
On my machine, I can compile the project just fine and it seems to work perfectly.

**Comment by erebe** [comment]
Hi,

There is no specific blocker, wstunnel can be compiled on ARM Mac. It is just that I haven't managed to cross-compile it with GitHub CI. I had some linker issue when I tried, but to be honest haven't dug too much into it.

I saw another rust project that managed to cross-compile on GitHub CI, I take a look at it and try to provide a Mac ARM binary.

**Comment by erebe** [comment]
If you have a Mac ARM, would you mind trying the new release and let me know if it is ok ? 
https://github.com/erebe/wstunnel/releases/tag/v8.4.3 


wstunnel_8.4.3_darwin_arm64.tar.gz  should be ok on MacOs ARM

**Comment by vercas** [comment]
It works perfectly, thank you very much. 😃

**Comment by erebe** [comment]
nice thank you :)
