### ISSUE TITLE
[DOC] Build requirements and instructions

### ISSUE THREAD

**Issue by IOOOTAlan** [erebe/wstunnel#2]
Greetings,

from what I've got, to build the project from sources one needs ghc-8+ (as some extensions are not implemented in previous versiosn) and cabal-install-1.24+ (required by ghc-8+).
Is this correct?

**Comment by erebe** [comment]
Sorry for the late response, for an unknown reason I haven't recieved an email when you posted an issue.

I have updated the readme with a section "how to build", let me know if it is clear enough

**Comment by IOOOTAlan** [comment]
Thanks @erebe,
will soon try to perform a build using your instructions.
I'll post here in case of issues.
