### ISSUE TITLE
arm32

### ISSUE THREAD

**Issue by fopina** [erebe/wstunnel#20]
Can we have a release for arm 32 bits? for Raspberry armv7l, because I've been using this through a linux VPS but wanted to use my RPi.

wstunnel is awesome btw (OpenVPN UDP over wstunnel working great), cheers!

**Comment by erebe** [comment]
Hello,

**Comment by fopina** [comment]
Will do :) in the meantime I’ll see if I send over my PR for IP restriction also supporting headers when behind reverse proxy as I’m using it with nginx in front (serving multiple vhosts, not only wstunnel :))

**Comment by fopina** [comment]
Works great cheers
