### ISSUE TITLE
Add certificate reloading mechanism to server

### ISSUE THREAD

**Issue by vercas** [erebe/wstunnel#202]
When using a wstunnel server with a short-lived certificate, such as those provided by Let's Encrypt, it can be disruptive to have to take down the entire server in order to use newly-obtained certificates.  
A mechanism for reloading certificates would be very useful. The most obvious way to trigger this is to use a Unix signal, e.g. `SIGHUP` like `nginx` does.  
This wouldn't have to close existing connections, and would only have to affect new connections.

**Comment by erebe** [comment]
Hello,

This would be a nice addition, indeed. After, I am not sure if people that requires this kind of flexibility will not use a reverse-proxy in front of wstunnel.

Anyway, it should not be too hard to add, so I keep it in the backlog.

**Comment by vercas** [comment]
Right now I'm using nginx in front of wstunnel to work around this, but yeah, it's really not a dealbreaker.

**Comment by erebe** [comment]
It should be implemented in release v8.5.2, can you let me know if it is ok for you https://github.com/erebe/wstunnel/releases/tag/v8.5.2 ?
