### ISSUE TITLE
Installing as a Windows service.

### ISSUE THREAD

**Issue by paolosezart** [erebe/wstunnel#203]
I have a request to the developers to add the ability to install wstunnel as a service in windows. That the program can run regardless of users on the server or client.

**Comment by erebe** [comment]
Hello,

This feature is out of the scope of wstunnel, but you can take a look at https://stackoverflow.com/a/15719678/1584186 to create your own service. It seems easy enough

**Comment by paolosezart** [comment]
Thank you. I knew about some of those tools. However, I was hoping to be able to install wstunnel without third party tools. I will use nssm as the most convenient for me for now.
