### ISSUE TITLE
ERROR tunnel{id="xxxxxxxxxxxxxxxxxxxxxxxxxxxxx" remote="127.0.0.1:51820"}: wstunnel::tunnel::client: failed to get a connection to the server from the pool: TimedOut

### ISSUE THREAD

**Issue by redsmokelinux** [erebe/wstunnel#206]
**### client**

> 
wstunnel client -L 'udp://:51820:127.0.0.1:51820?timeout_sec=0' wss://SERVER_IP:888

> ERROR tunnel{id="xxxxxxxxxxxxxxxxxxxxxxxxxx" remote="127.0.0.1:51820"}: wstunnel::tunnel::client: failed to get a connection to the server from the pool: TimedOut

> WARN wstunnel::tcp: Cannot connect to tcp endpoint SERVER_IP:888 due to timeout of 10s elapsed    

client side is not working

**Comment by erebe** [comment]
Hello,

Can you describe your setup ? Do you expect some firewall in the middle ?

Most likely the port 888 is blocked, packet are dropped. Try starting the server on a on a well known poet. i.e: 443 or try some other ones.

**Comment by redsmokelinux** [comment]
Its not blocked. I'm using azure for my wireguard setup. i have open port 888 and 51820. To tunnel my wireguard traffic through tls I want to use wstunnel.
