### ISSUE TITLE
upgrade guide for v5.0 to v9.*

### ISSUE THREAD

**Issue by sajjadnasiribrn** [erebe/wstunnel#212]
hello and thankyou for this helpful package.
I am using wstunnel 5.0 + cloudflare + v2ray, and everything is working well. However, when I try to upgrade to version 8.5, I encounter issues despite rewriting the commands based on this version. Please guide me on how to rewrite these commands for version 8.5 :

in client side: 
wstunnel -L 0.0.0.0:443:localhost:443 wss://server.example.xyz:2087

in server side:
wstunnel  --tlsCertificate=/etc/letsencrypt/live/server.example.xyz/cert.crt --tlsKey=/etc/letsencrypt/live/server.example.xyz/privkey.key  --server wss://0.0.0.0:2087 -v

**Comment by erebe** [comment]
Hello,

What kind of issue ?
The equivalent for your command should be 
```
 wstunnel client -L "tcp://0.0.0.0:443:localhost:443" wss://server.example.xyz:2087
 and 
 wstunnel server --tls-certificate=/etc/letsencrypt/live/server.example.xyz/cert.crt --tls-private-key=/etc/letsencrypt/live/server.example.xyz/privkey.key wss://0.0.0.0:2087
```

**Comment by sajjadnasiribrn** [comment]
I did this, but it didn't work. The client service didn't run. The server-side service ran, but maybe it's because of the lack of the -v option. I don't know.

**Comment by erebe** [comment]
Woud you mind start the client and the server with `--log-lvl=TRACE`, try to connect and pasting the output ?

**Comment by sajjadnasiribrn** [comment]
i did that and see these errors:

wstunnel.service: Failed to execute /usr/bin/wstunnel: Exec format error
systemd[5293]: wstunnel.service: Failed at step EXEC spawning wstunnel: Exec format error
systemd[1]: wstunnel.service: Main process exited, code=exited, status=203/EXEC

**Comment by erebe** [comment]
It seems the binary is not for your CPU architecture.
Which binary are you using and what is the OS & CPU you are running it on ?

**Comment by sajjadnasiribrn** [comment]
lscpu is like that:
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  1
  On-line CPU(s) list:   0
Vendor ID:               GenuineIntel
  Model name:            Intel Xeon E312xx (Sandy Bridge, IBRS update)
    CPU family:          6
    Model:               42

and im using arm64 version of your package.

**Comment by erebe** [comment]
Hum strange would you mind doing a
```
ls -l wstunnel

and 

file wstunnel 
```

What is happening if you launch the binary directly from a shell/terminal ?

**Comment by sajjadnasiribrn** [comment]
wstunnel: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, with debug_info, not stripped

**Comment by sajjadnasiribrn** [comment]
my problem is in client side. in server side service start correctly.
