### ISSUE TITLE
"publicness"

### ISSUE THREAD

**Issue by fopina** [erebe/wstunnel#22]
Even though there is already an option to restrict proxying to single target, the default error message is quite unique which led me to check [shodan](https://www.shodan.io/search?query=%22Invalid+tunneling+information%22) for it.

So maybe it would make sense to update that text to `Bad request` or something like the default 400 response bodies?

Also, tried to see how to add a "HTTP header check" but my haskell is quite `Nothing`.  

Would that be a simple "security" feature, passing `--key RandomKeyString` on both server and client, client sends it over in an HTTP header during WS handshake and server makes sure it matches or just 400 on it

**Comment by erebe** [comment]
Hello,
I never thought too much about wstunnel being stealth, your request follow this one https://github.com/erebe/wstunnel/issues/16 (which I forgot about). I am a bit reluctant to add those features as I will need to re-do all the releases for each architectures, which takes me a lot of time that I don't have in quantity those days...
But I note the request, If I have enough of them in the backlog I will do a proper new release.
(I would like also to add the possibility to generate fake tls certificates at every startup)

Regarding the `--key RandomKeyString` you can already do it with with 
```

**Comment by fopina** [comment]
Right `upgradePathPrefix` would be good enough if it was the only path working, but yes, I guess in my case, as I already have nginx in front of it, I could block everything else there (including the default page for root path, prevent being flagged in shodan and alikes). Need to see the best way to do that as I'm using jwilders nginx-proxy docker in my setup :)

I'll try to send you a PR using qemu in travis for all your builds but it's a bit time-consuming to test when it takes so long to get `stack` ready to compile hehe

**Comment by erebe** [comment]
done in release v3.1
https://github.com/erebe/wstunnel/releases/tag/v3.1
