### ISSUE TITLE
[windows] wstunnel force close stdio

### ISSUE THREAD

**Issue by AnorBanantje** [erebe/wstunnel#229]
**Describe the bug**
When connection is not successfully started / ended or something wrong in command but command is valid to start process is not possible to kill wstunnel with CTRL +C / CTRL + Z?
Only cmd, powershell window close help here.

**To Reproduce**
Start powershell or CMD execute:
ssh -o ProxyCommand=".\wstunnel.exe client -L stdio://%h:%p https://127.0.0.1" user@127.0.0.2
Try kill process with CTRL +C or CTRL + Z

**Expected behavior**
when wstunnel is working CTRL+C or CTRL+Z most close wstunnel and application which uses it.

**Comment by erebe** [comment]
Indeed, I manage to reproduce on Windows. 
Regarding how to fix it, for now I don't know, as it seems peticular to how windows handle the raw mode of the terminal.

**Comment by Maxime-JULLIEN** [comment]
Hi all,

I am encountering the same issue as described above. However, in my case, it's particularly blocking in Datagrip, which uses this connection. Datagrip fails to close an existing connection properly, forcing me to terminate all processes manually to restart them. This is significantly impacting my workflow. 

Could we prioritize a fix for this ?

**Comment by erebe** [comment]
Hello,
Will try to take another look at it in the coming days

**Comment by erebe** [comment]
hi back,

Would you mind trying this pre-release and let me know https://github.com/erebe/wstunnel/releases/tag/v9.5.0 ?
CTRL+C should be handled, if you hit twice ctrl+c it should exit normally.

**Comment by erebe** [comment]
I released the v9.5.0 with the changes.
Feel free to re-open if needed
