### ISSUE TITLE
TLS 1.3 support

### ISSUE THREAD

**Issue by PriceChild** [erebe/wstunnel#23]
```
ERROR :: Cannot do tls handshake with the server
DEBUG :: ====
HandshakeFailed (Error_Protocol ("expecting server hello, got alert : [(AlertLevel_Fatal,ProtocolVersion)]",True,HandshakeFailure))
```

> Ha sorry, I can't upgrade to the latest LTS due to this issue #8
> I need to make some changes in order for wstunnel to work with the latest tls package.
> 
> Sadly I don't have much free time right now, so it may take time before I upgrade it.

_Originally posted by @erebe in https://github.com/erebe/wstunnel/issues/17#issuecomment-478948961_

**Comment by PriceChild** [comment]
Given the original comment about 'LTS' I'm not sure if 'tls' is a typo, but quoted above.

**Comment by PriceChild** [comment]
Applying the diff in https://github.com/erebe/wstunnel/pull/18 to allow pulling in a newer `network-conduit-tls` doesn't allow a connection to my tls 1.3 only server.

**Comment by ygoe** [comment]
The latest release 3.0 is from early 2020. There's no note about TLS 1.3 support for that. Has this been added already?

**Comment by erebe** [comment]
Hello,
You can try the artifacts from this build https://github.com/erebe/wstunnel/runs/862673183, TLS 1.3 should be working !
