### ISSUE TITLE
Extra layer of stealth -  content-length with auto counted content length.

### ISSUE THREAD

**Issue by AnorBanantje** [erebe/wstunnel#231]
**Is your feature request related to a problem? Please describe.**
Auto add content-length with right number of length to make traffic more hidden in http2

**Describe the solution you'd like**
when you add flag --enable-content-length 
header content-length: (right number of length counted by wstunnel) is added to every request

**Describe alternatives you've considered**
I through that i can set static number but it is easy to detect with inspection that content-length does not match real length but tried it too.

content-length: 0 = can't connect to ssh after wstunnel

content-length: 1000 = can connect but can't execute commands ( error )

content-length: 5000 = can connect + can execute commands but error when use sock proxy to browse internet

content-length: 19503829(random big number) = can everything but i think it could be too easy detected.

**Comment by erebe** [comment]
Hello,

It is not possible for wstunnel to pre-set the content-length headers. As it depends on the amount of traffic you transfer in the tunnel, it cannot be known in advance to be set in the header request.

Your only solution is to set a big number indeed. If you are afraid of it to be too noticeable, you can randomize it :)

**Comment by AnorBanantje** [comment]
hmm looks like only wstunnel self closes connection when content-length is too low for connection or when connected and number of packets which are sent is bigger than content-length than wstunnel server drop connection.

Is maybe possible to set attribute with wstunnel server **--ignore-content-length** which ignores content-length or removes it inside wstunnel and then parse further request?

Alternative could be HAProxy between frontend HAproxy and wstunnel which removes this header but it wil be overkill for so little task and haproxy gets timeouts when work in layer 7 with wstunnel hmm


Then eventually we could use random number here which help gets through firewall but is ignored in wstunnel server.
wstunnel client --set-content-length 1000 --content-length-variation 500 (which could get random values between 500 and 1500

but only --ignore-content-length could "be need to have" for firewall bypass. Of course if it is possible.
client side we could alltime set self --http-headers content-length:1294

**Comment by erebe** [comment]
Sadly, I can't remove the handling of the content-type from wstunnel, as it is directly backed into the HTTP library, and I don't have anyway to control its behavior on that point.

I think you are fine setting a random big number as content-length
