### ISSUE TITLE
Add path support

### ISSUE THREAD

**Issue by ikidou** [erebe/wstunnel#24]
Hello,

if the 'Client' is `wstunnel` it 's can not connect to wstunnel server in this case:

```
Client <---> Caddy  <----proxy ws with fixed path ---> wstunnel server <---> tcp server
```

So,can you add path support?

thanks.

**Comment by erebe** [comment]
Hello,
I don't understand your question/problem. 
Can you explain it a bit more ?

**Comment by ikidou** [comment]
Hello, the request path is useful for reverse proxy,but wstunnel has special path like `/wstunnel/tcp/127.0.0.1/8080`, so if the wstunnel server behind the reverse proxy,it's not working.

If reverse proxy server proxy `/wsTotcp` to wstunnel server, How can I connect to wstunnel server use wstunnel  command?

I tried to add ` --upgradePathPrefix=/wsTotcp` ,wstunnel server said "Rejecting connection"

**Comment by erebe** [comment]
Well if you are using à reverse proxy, you can use URL rewrite feature. That's available with nginx, apache, haproxy.
