### ISSUE TITLE
Unsupported SOCKS version `67`

### ISSUE THREAD

**Issue by Guiraud** [erebe/wstunnel#243]
**Describe the bug**
Firefox  : 
when I activate the proxy on Firefox and I have this error : 
2024-03-16T11:49:07.777129Z WARN wstunnel::socks5: Rejecting socks5 cnx: Unsupported SOCKS version `67`.

**To Reproduce**
on my server : 
```
wstunnel server wss://[::]:8080
```
on my client : 
```
wstunnel client -L socks5://127.0.0.1:8888 --connection-min-idle 5 wss://myRemoteHost:8080
```
The setup of my Firefox : 
```
    Proxy HTTP:
        127.0.0.1: This is the loopback address, referring to the local machine itself.
        Port 8888: This is the port number configured for the proxy server.
    Using HTTPS (Also use this proxy for HTTPS): 
    This checkbox is selected, indicating the proxy should be used for HTTPS traffic as well.
    Proxy HTTPS: Same configuration as Proxy HTTP.
    Hôte SOCKS (SOCKS Host):
        127.0.0.1: Same as Proxy HTTP.
        Port 8888: Same as Proxy HTTP.
    SOCKS v4: This option is not selected.
    SOCKS v5: This option is selected.
```
**Expected behavior**
I expecting my public address to the same as the server IP
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Apple mac 2 pro on Sonoma
 -  Firefox on mac os
 - 123.0.1

Additional information : 
I'm using on my local computer the v9.2.3 wstunnel compiled with rust. I didn't have any issue.

**Comment by erebe** [comment]
Hello,

You must not set the HTTP proxy. Only socks5 should be filled
![image](https://github.com/erebe/wstunnel/assets/854278/aa3e0bc7-234d-4dc8-969d-b5c6acfb6a8c)
