### ISSUE TITLE
It stops when the number of requests increases

### ISSUE THREAD

**Issue by V2RVPNShop** [erebe/wstunnel#249]
When the number of requests increases, the packet loss increases.
When the number of requests gets too high, it stops and I have to restart the service.
I restart the service every 5 minutes (using Crontab), the problem is solved to some extent.

 - OS: Ubuntu 22
 - Version: 9.2.4

**Comment by V2RVPNShop** [comment]
This is how I use WSTunnel:
`wstunnel server wss://[::]:8443
wstunnel client -L tcp://0.0.0.0:80:localhost:80 -L tcp://0.0.0.0:443:localhost:443 -L tcp://0.0.0.0:512:localhost:512 -L tcp://0.0.0.0:530:localhost:530 wss://sub.domain.ir:8443`

After a while, when the number of connections on a port increases, that port will go out of listening mode.
And I need to restart the wstunnel service.
![WSTunnel](https://github.com/erebe/wstunnel/assets/155872526/f2269f33-3d27-4f1f-a81f-be31ca468c5f)
I also used the reverse mode and I still have this problem.

**Comment by erebe** [comment]
I thanks for providing more information.
Would you mind testing this pre-release and let me know if it fix your issue https://github.com/erebe/wstunnel/releases/tag/v9.2.5

**Comment by V2RVPNShop** [comment]
Hi,
The problem is solved in version 9.2.5.
Thank you very much for your attention and quick fix.
