### ISSUE TITLE
MacOS: Connectivity Issue

### ISSUE THREAD

**Issue by sujaysarkhel** [erebe/wstunnel#25]
I'm trying to use this in my Mac OS (Mojave) by installing the "wstunnel-macos" binaries but for some reason, I can't get it to work. Post installation, I execute the following command to get the process started:

`wstunnel -D 8888 wss://{url}`
I see the following getting printed:
`Starting socks5 proxy ServerSettings {listenOn = 8888, bindOn = "127.0.0.1"}`

However, after that, when I try to connect to any specific service, I see the following errors on the command line (because of which the connectivity fails):
```
wstunnel: Data.Binary.Get.runGet at position 0: not enough bytes
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:342:5 in binary-0.8.3.0:Data.Binary.Get
CLOSE tunnel :: 127.0.0.1:8888 <==WSS==> {url} <==TCP==> {some_ip}
```

I'm not sure what I'm doing wrong though. Would appreciate any help or pointers with this one. Thanks!

**Comment by erebe** [comment]
Hello,
Can you tell me more about how you connect to the socks5 proxy ?
How do you do your setup in order to use it ?

**Comment by sujaysarkhel** [comment]
> Hello,
> Can you tell me more about how you connect to the socks5 proxy ?
> How do you do your setup in order to use it ?

I'm using Firefox to connect. I've updated the proxy settings for the browser by doing something like this:
<img width="702" alt="Screen Shot 2019-08-06 at 9 54 39 AM" src="https://user-images.githubusercontent.com/37962357/62559974-ef0c1c00-b830-11e9-903c-5506da1e0a1d.png">

The error that I pasted above happens when I try to connect to an ES client using the proxy. Note that I've a Linux box as well & things work like charm from this machine. It's just that I see this issue crop up on my Mac OS

**Comment by xask00** [comment]
@erebe Seeing the exact same error on windows binary as well,
Only the linux binary works
Something wrong with the mac/win binaries ?

**Comment by erebe** [comment]
Not that I am aware of @xask00 
I will give it a look when I come back from vacation (in ~2 weeks)

**Comment by erebe** [comment]
In the mean time can you both,

1. Start your server and client with verbose mode activated
2. Try to use wstunnel
3. Send me the logs of both client and server

Thanks
