### ISSUE TITLE
No file descriptors available Error

### ISSUE THREAD

**Issue by V2RVPNShop** [erebe/wstunnel#251]
Hi,
After a few hours of running wstunnel as below, I got this error.
`wstunnel server wss://[::]:8443`

![image](https://github.com/erebe/wstunnel/assets/155872526/37d2a252-fcb4-4eeb-83fa-fc14a3d8644b)

This is my limits info:
![image](https://github.com/erebe/wstunnel/assets/155872526/17159c93-40ea-4093-8166-9d4f3c5c786a)

**Comment by erebe** [comment]
This is not related to wstunnel but to your system/workload, file descriptors are not infinite.
Either spread the load on another machine, or if you have too many idle connections, use a reverse proxy to force close inactive connections after a timeout

**Comment by V2RVPNShop** [comment]
Hi,
If I run wstunnel like this on the client side, will the problem be solved?
`wstunnel client -L 'tcp://0.0.0.0:80:localhost:80?timeout_sec=60' -L 'tcp://0.0.0.0:443:localhost:443?timeout_sec=60' wss://sub.domain.ir:8443`

Thanks for your answer

**Comment by erebe** [comment]
It would indeed, but the timeout is only implemented for *udp*. As for Tcp we already know when to terminate the connection.

I strongly recommend you installing nginx/haproxy in front of wstunnel to handle those cases.
