### ISSUE TITLE
request add standalone socks5 server feature and ...

### ISSUE THREAD

**Issue by netoffice-zz** [erebe/wstunnel#258]
i tested, wstunnel is very excellent, transmission speed (over ws) is far higher than frp (over tcp), gost (over tcp), goproxy (over tcp), wssocks (over ws), and wstunnel is similar to ssh，i like it!

if wstunnel add follow features, it's more stronger:
1. standalone socks5 server ( wstunnel server socks5://ip:port )
2. tunnel transport add tcp/kcp (wstunnel server tcp://ip:port), i think  transmission speed can improve 10~20% over it

I know from the name of wstunnel, above feature requests are not suitable, but add a small amount of rust code, executable file size remains almost unchanged, but it can provide more stronger feature.

**Comment by erebe** [comment]
Hello,

Thank you for the kind words, but sadly I don't plan to add new transport protocol beside what works with http :(
