### ISSUE TITLE
store location nginx

### ISSUE THREAD

**Issue by QuazyMorda** [erebe/wstunnel#26]
Please tell me if it is possible to work with another location.
Example client connect:
Its work: 
 /usr/bin/docker run --rm -it -p 9091:9091/tcp --name wstunnel local/wstunnel:1.2 -v -L 0.0.0.0:9091:192.168.0.3:9091 wss://domain.com:443
WAIT for tcp connection on 0.0.0.0:9091
DEBUG :: Oppening tcp connection to domain.com:443
DEBUG :: Doing tls Handshake
DEBUG :: Oppening Websocket stream

Use store locations do not work:
 /usr/bin/docker run --rm -it -p 9091:9091/tcp --name wstunnel local/wstunnel:1.2 -v -L 0.0.0.0:9091:192.168.0.3:9091 wss://domain.com:443/storelocation
WAIT for tcp connection on 0.0.0.0:9091
DEBUG :: Oppening tcp connection to Error writing log message: Invalid port number `443/storelocation`
CallStack (from HasCallStack):
  error, called at app/Main.hs:82:31 in main:Main (original message: DEBUG :: Oppening tcp connection to DEBUG :: Oppening tcp connection to Error writing log message: Invalid port number `443/storelocation`
  

/usr/bin/docker run --rm -it -p 9091:9091/tcp --name wstunnel local/wstunnel:1.2 -v -L 0.0.0.0:9091:192.168.0.3:9091 wss://domain.com/storelocation:443
WAIT for tcp connection on 0.0.0.0:9091
DEBUG :: Oppening tcp connection to domain.com/storelocation:443

Example Nginx config:
...
    location /storelocation {
      proxy_pass http://192.168.0.3:8080;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header        Host            $host;
      proxy_set_header        X-Real-IP       $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;
    }
    
Thank you.

**Comment by erebe** [comment]
Hello,
Sorry for the delay I haven't seen the notification of your issue.

You can use the prefixPath feature https://github.com/erebe/wstunnel/issues/14
Basically use the option, --upgradePathPrefix=storelocation and it should match your nginx rule

**Comment by QuazyMorda** [comment]
Thanks!
It works, the option is set on the client side of the utility.
