### ISSUE TITLE
Publish to crates.io?

### ISSUE THREAD

**Issue by TobiX** [erebe/wstunnel#265]
It would be nice if wstunnel would be available via `crates.io`, so one can just `cargo install wstunnel` to get the lastest version.

Maybe contact @losfair if they would be willing to give up the name on crates.io - that project looks dormant.

**Comment by erebe** [comment]
Hello,

I dont plan to do that as I dont want to polute creates.io with binaries. In my mind creates.io is for librairies of stuff related to cargo. But I dont consider cargo as a package manager, so I dont plan to publish it there. Maybe someday if I turn wstunnel as a librairie

**Comment by flokli** [comment]
I have a usecase for the library, opened https://github.com/erebe/wstunnel/issues/286.
