### ISSUE TITLE
UDP Support

### ISSUE THREAD

**Issue by nishuo** [erebe/wstunnel#27]
Can I enable TCP/UDP listening at the same time?

**Comment by nishuo** [comment]
When I start, use the -u parameter, TCP does not work

**Comment by nishuo** [comment]
When I use wstunnel, it has good performance and stability, and it would be better if can listen to TCP UDP at the same time.

**Comment by erebe** [comment]
Hello,
While I hear, it is not going to happens due to the amount of work necessary to make this change.
You can just start two clients if you want to listen in TCP and UDP at the same time :)

**Comment by nishuo** [comment]
@erebe I need to forward multiple rules, including TCP/UDP, and keep it clean, and if you accept, I can pay.
