### ISSUE TITLE
Issues with traefik

### ISSUE THREAD

**Issue by Yaya48** [erebe/wstunnel#271]
Hello, i'am using traefik behind wstunnel but i get a lot of instability 
![image](https://github.com/erebe/wstunnel/assets/34249303/33320507-d8a3-428d-a86d-0e100215ce0a)

When i'm trying to connect, my domain name is behind cloudfalre but i do not use proxy option. I use just for DNS so it shouldn't cause issues. in traefik i enabled tls passthough for the service.

![image](https://github.com/erebe/wstunnel/assets/34249303/b3b92256-7601-46e7-9e34-0441a71585e5)
![image](https://github.com/erebe/wstunnel/assets/34249303/e5d18e0e-1551-4400-8309-42ff3dba14db)

I'm using wstunnel to passthrough ovpn. and i'm using last version of wstunnel and traefik 3.0

**Comment by erebe** [comment]
Like that I cannot help you much, as I never used traefik.

Would you mind sharing the log of the client when started in debug ? `--log-lvl=debug`

**Comment by Yaya48** [comment]
Hello, yeah i will. I've also tried without traefik and yeah it work well better instant connection every time + also faster internet access. and also i moved from ovpn to wireguard.
