### ISSUE TITLE
eprintln of "Starting STDIO server"

### ISSUE THREAD

**Issue by daaku** [erebe/wstunnel#275]
Would it be reasonable to move this to use logging so it is silenced when `--log-level=ERROR` is used?

https://github.com/erebe/wstunnel/blob/0595e230504d24de6587987a355bc3d1697ae789/src/stdio.rs#L6

**Comment by daaku** [comment]
Nope, no issues. Just visual noise. Could the logger use stderr in this mode? Feel free to close the issue if it's not worth the trouble.

Also, thanks for making this. It's working great to reverse proxy ssh connections. It's super light weight, low memory usage, network performance is great too.

**Comment by erebe** [comment]
stderr is a good idea, let me check if I can manage to redirect the logger to it

**Comment by erebe** [comment]
Would you mind trying this pre-release and let me know if it works for you ?

**Comment by daaku** [comment]
Does the trick - thank you!
