### ISSUE TITLE
Suggestion: please do not re-release the same version (don't stealth upgrade)

### ISSUE THREAD

**Issue by i0ntempest** [erebe/wstunnel#277]
I maintain a wstunnel port on MacPorts and I've found out and had to fix fetch failures caused by checksums changes, [multiple times](https://github.com/macports/macports-ports/commits/fbd40818a0db6b0d7e499e35e52952b9b3889fa9/net/wstunnel/Portfile). Stealth upgrades require inconvenient special handlings in MacPorts and it might take me days to discover in the first place (or someone opening a ticket, and I assume it's similar for Homebrew). So may I request you to stop doing that and just make new minor releases for fixes?

**Comment by erebe** [comment]
I can do that, I was not aware that downstream package was so fast. Usually if i made a mistake and réalise it within a few hours, i update the release.

But ok, i will avoid doing it in the future.

Ps: i released q new minor
