### ISSUE TITLE
process doesn't exit when using stdio mode and connection errors out

### ISSUE THREAD

**Issue by daaku** [erebe/wstunnel#279]
I'm connecting to an ssh server using something like this:

```
Host example.com
  ProxyCommand wstunnel client -L stdio://localhost:22 wss://example.com
```

When the network goes down, the connection fails with something like:

```
ERROR wstunnel::tunnel::transport::io: error while reading from tunnel rx Connection reset by peer (os error 104)
```

At this point the `wstunnel` process should exit with some non-zero exit code. Instead it just waits around doing nothing.

**Comment by erebe** [comment]
Hello,

Would you mind trying this pre-release and let me know if it fixes your issue https://github.com/erebe/wstunnel/releases/tag/v9.5.3-rc1 ?

**Comment by erebe** [comment]
should be fixed in release https://github.com/erebe/wstunnel/releases/tag/v9.6.0

let me know if it is not the case

**Comment by daaku** [comment]
Thanks, fix looks good!
