### ISSUE TITLE
Unable to ping wireguard server over ipv6

### ISSUE THREAD

**Issue by soudaburger** [erebe/wstunnel#280]
**Describe the bug**
* Client device has a "public" ipv6 IP address.
* Server has public ipv6 IP address
* Wireguard server is listening on an internal ipv4 address.

* Server started with `/usr/local/bin/wstunnel server wss://0.0.0.0:443 --restrict-to 127.0.0.1:51820`

I am unable to ping the wireguard server from the client after the tunnel is established.  With the exact same setup, but with the server having an IPv4 address, everything appears to work fine. 

**Expected behavior**
I would expect to be able to ping my wireguard server over an established ipv6 tunnel.

**Desktop (please complete the following information):**
* client: wstunnel 9.5.2
* server: wstunnel 9.5.2

**Additional context**
I don't necessarily know if this is a bug or simply missing some context.  Any help would be greatly appreciated.

**Comment by erebe** [comment]
I just try with my server and i don't have any issuem so my guess it is a problem with your config

I connect with a tunnel in ipv6 to my server, but request to forward/connect to an ipv4 after
![image](https://github.com/erebe/wstunnel/assets/854278/9376a4ef-1ae0-4be5-acd4-fa58fe12828b)

me wireguard client config looks like that
```
❯ cat /etc/wireguard/wg0.conf
[Interface]
Address = 10.200.0.252/32, fd00:cafe::252/128
PrivateKey = xxxx

[Peer]
PublicKey = xx
AllowedIPs = 10.200.0.0/24, fd00:cafe::/32
Endpoint = 127.0.0.1:9995
PersistentKeepalive = 20
```

**Comment by soudaburger** [comment]
Are you doing an iptables magic to get them to work over ipv6 also?  I'd love some example configs if you can provide something or have any pointers.  Any help would be appreciated! thanks!

**Comment by soudaburger** [comment]
I appreciate your help here... I was finally able to get it all working.  This is such a fantastic tool! Much appreciated!
