### ISSUE TITLE
wstunnel 9.6.0 not working on arm64

### ISSUE THREAD

**Issue by soudaburger** [erebe/wstunnel#281]
**Describe the bug**
Binary doesn't run.  I'm assuming that's the not the right tarball or I'm missing some dependency that isn't super obvious?

**To Reproduce**
See steps down below.

**Expected behavior**
Binary should run.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian ARM64
 - Version: Wstunnel 9.6.0

**Additional context**
Downloaded from tarball:
```bash
debian@debian:~$ wget https://github.com/erebe/wstunnel/releases/download/v9.6.0/wstunnel_9.6.0_linux_arm64.tar.gz
debian@debian:~$ tar xf wstunnel_9.6.0_linux_arm64.tar.gz
debian@debian:~$ sudo mv wstunnel /usr/local/bin/wstunnel
debian@debian:~$ sudo chmod +x /usr/local/bin/wstunnel
debian@debian:~$ ldd /usr/local/bin/wstunnel
/usr/local/bin/wstunnel: error while loading shared libraries: /lib/aarch64-linux-gnu/libc.so: invalid ELF header
debian@debian:~$ uname -a
Linux debian 6.1.0-21-arm64 #1 SMP Debian 6.1.90-1 (2024-05-03) aarch64 GNU/Linux
debian@debian:~$ /usr/local/bin/wstunnel
-bash: /usr/local/bin/wstunnel: cannot execute: required file not found
debian@debian:~$ ls -l /usr/local/bin/wstunnel
-rwxr-xr-x 1 debian debian 8483760 May 25 05:02 /usr/local/bin/wstunnel
debian@debian:~$ file /usr/local/bin/wstunnel
/usr/local/bin/wstunnel: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, stripped
```

**Comment by erebe** [comment]
ha indeed, I messed up the packing while adding the android build.
Going to make a new release

**Comment by soudaburger** [comment]
Oh good, i'm not imagining things... Fantastic news... I appreciate you!

**Comment by erebe** [comment]
Should be fixed in the latest release https://github.com/erebe/wstunnel/releases/tag/v9.6.1

Sorry about that

**Comment by soudaburger** [comment]
Confirmed working... thank you!
