### ISSUE TITLE
windows run error

### ISSUE THREAD

**Issue by goldsoft8888** [erebe/wstunnel#282]
c:>\ wstunnel client -L 'udp://51820:localhost:12345?timeout_sec=0' wss://my.server.com:443
error: invalid value ''udp://51820:localhost:12345?timeout_sec=0'' for '--local-to-remote <{tcp,udp,socks5,stdio,unix}://[BIND:]PORT:HOST:PORT>': Invalid local protocol for tunnel 'udp://51820:localhost:12345?timeout_sec=0'

For more information, try '--help'.

**Comment by goldsoft8888** [comment]
root@armbian:~# ./wstunnel client -L 'udp://51820:localhost:51820?timeout_sec=0' wss://my.server.com:443
2024-05-28T12:18:51.920396Z  INFO wstunnel::udp: Starting UDP server listening cnx on 127.0.0.1:51820 with cnx timeout of 0s

**Comment by erebe** [comment]
Not an expert but on windows you need to use " instead ' to pass argument.

`error: invalid value ''udp://51820:localhost:12345?timeout_sec=0'' `  wstunnel receive your argument with the quote in it
