### ISSUE TITLE
Ram usage

### ISSUE THREAD

**Issue by nvdmhd** [erebe/wstunnel#283]
Hello, I am using wstunnel to connect my two servers, and I use WebSocket to bypass filtering. The problem I have is that each time the server's RAM fills up, the server hangs, and I have to manually restart the wstunnel service to clear the cache and solve the issue. Is there a way to automate this process? I even tested with crontab and a bash file, but only manual restart works.

**Comment by nvdmhd** [comment]
I will send a screenshot of htop
1. 1 TB VIRT and almost 130 MB RES
2. I have 40-50 inbounds in xui panel
3. I use Websocket (ws+tls) using Nginx and cloudflare
4. I did not get last one

![Screenshot 2024-05-28 130953](https://github.com/erebe/wstunnel/assets/45994182/4d2a37f8-11a7-412d-93eb-79d802783b1a)

**Comment by erebe** [comment]
hum, ok, when you mean the server RAM fill up you mean your server and not wstunnel ?
How do you know it is wstunnel taking too much RAM ?

**Comment by bytejedi** [comment]
I think he's using the Haskell version. The Haskell GC?

**Comment by erebe** [comment]
@bytejedi Thank you, you are right, I haven't noticed indeed.

@nvdmhd You are using an old release of wstunnel please upgrade to the latest version https://github.com/erebe/wstunnel/releases/tag/v9.6.1

your command line should change a bit and be something like `wstunnel client -L tcp://0.0.0.0:443:localhost:443`

**Comment by nvdmhd** [comment]
so the version is the problem? alright I will give it a try thanks for response

**Comment by erebe** [comment]
feel free to re-open of needed
