### ISSUE TITLE
Binary for aarch64?

### ISSUE THREAD

**Issue by mccoy** [erebe/wstunnel#29]
I know it is a bit of an ask, but as a haskel noob I have found the process for getting a build environment up and running for arm64 to be a bit more complicated than I was prepared for.  Since you have an armv7 environment I am hoping that an aarch64 build is a simple tweak for you rather than the long and semi-borked process that they rest of us face...

**Comment by erebe** [comment]
Can you try this version https://github.com/erebe/wstunnel/releases/download/v3.0/wstunnel-aarch64 and let me know the outcome ?
