### ISSUE TITLE
docker documentation

### ISSUE THREAD

**Issue by deepakkoirala** [erebe/wstunnel#297]
I really wanted to run this project in docker because it isolates everything. I am not from a rust background.

I know there is a Dockerfile in the repo. I wish there were some documentations for docker commands to run this project in docker.

Since with docker we can run any apps using one liners. It would help some people at some point including me.

**Comment by erebe** [comment]
Hello,
Docker images are available here https://github.com/erebe/wstunnel/pkgs/container/wstunnel
Command are the same than the binary, you can start your docker as usual
