### ISSUE TITLE
UDP tunnel is mono-directional?

### ISSUE THREAD

**Issue by IOOOTAlan** [erebe/wstunnel#3]
Greetings,

while trying to forward an UDP port through the tunnel, I discovered that the wstunnel client seems to keep the port busy because it's apparently listening for datagrams to forward through the tunnel.
This, however, seems to make it impossible to receive anything from the said port from the remote end, as any application trying to listen for datagrams gets a "port is busy" error.
Is this expected behavior?

**Comment by erebe** [comment]
I am not sure to understand.
Can you provide an example and explain the current behavior and what you are expecting ?
