### ISSUE TITLE
Build In Centos 32bits Machine

### ISSUE THREAD

**Issue by asterdeve** [erebe/wstunnel#300]
Last 3 days I have tried a lot even exactly before I started to write here, I didn't found any proper guide to build this tunnel on old linux machine like **Centos-6.10 i386**

Yes I know its quite old version of linux distro but still many people are using because of some needs & I am one of them, I hope someone know how to build latest of wstunnel or if there is already binary file hope someone can share with me  **ldd (GNU libc) 2.12** 

Thanks for you attention! hope I will get some good response.

**Comment by erebe** [comment]
I made a new release https://github.com/erebe/wstunnel/releases/tag/v9.7.1 and added a binary for linux 32bits ` wstunnel_9.7.1_linux_386.tar.gz`

Let me know if it is working for you

**Comment by asterdeve** [comment]
Thank you so much for your fast feedback. 

I want small favor from you, I want to use this to registered with SIP & bypass all traffic using wstunnel.

Let's say I have sip port 6050 in server end & 6051 client how can I bypass firewall blockage bypass securely all traffic using wstunnel.

I have tried with many ways but I didn't succeed sip didn't got registered, May be some config I missed, hope you can help me.

Thanks for your help.
