### ISSUE TITLE
add http/https proxy Options

### ISSUE THREAD

**Issue by hyjk555** [erebe/wstunnel#303]
Some software only supports http or https proxy listening,Does not support socks5

Hope add http/https proxy Options

So I had this idea

Windows does not support tproxy+tcp model
wstunnel client -L tproxy+tcp://[::1]:8088 https://xxxxx:9082
thread 'main' panicked at src\main.rs:1154:25:
Transparent proxy is not available for non Linux platform
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by hyjk555** [comment]
> You mean for the client to act as an http proxy ? Can be a good idea yes if it is the case.

Yes.
If the author has time, they can consider this idea

**Comment by hyjk555** [comment]
> You mean for the client to act as an http proxy ? Can be a good idea yes if it is the case.

Yes.
If the author has time, please consider this idea

**Comment by erebe** [comment]
Hello,

You can try this new pre-release https://github.com/erebe/wstunnel/releases/tag/v9.8.0-rc1 
There is a new local and remote tunnel that start an http proxy. It support login/password also

```
-L, --local-to-remote <{tcp,udp,socks5,stdio,unix}://[BIND:]PORT:HOST:PORT>
          Listen on local and forwards traffic from remote. Can be specified multiple times
          examples:
          'http://[::1]:1212'              =>       start a http proxy on port 1212 and forward dynamically requested tunnel
          'http://[::1]:1212?login=admin&password=admin' => start a http proxy on port 1212 and only accept connection with login=admin and password=admin
```


Let me know if it works for you
