### ISSUE TITLE
Found a DNS leak problem

### ISSUE THREAD

**Issue by buswisir** [erebe/wstunnel#304]
Proxy Wireguard traffic. After the configuration is completed, it is found that there seems to be a DNS leak problem. You can detect the real IP by opening this website:
https://ipleak.net

**Comment by erebe** [comment]
Most likely, you haven't configured properly your wireguard client. Can you please share your config

**Comment by buswisir** [comment]
The client added a static route and modified the allowed IPs to: 0.0.0.0/1, 128.0.0.1/1
Then, the problem of DNS leak is solved. Thank you very much for your prompt reply.

**Comment by buswisir** [comment]
At this time, use the Firefox browser to enable the DoH function and select a DNS resolver that supports DoH. Then open the https://ipleak.net website for testing. You do not see the local ISP DNS; but after canceling the DOH function of Firefox, open it again. When testing the https://ipleak.net website, you will see that among the many DNSs, there is a local DNS. How to solve this problem?

**Comment by buswisir** [comment]
OK, thank you very much for your help
