### ISSUE TITLE
Auto-generate remote port

### ISSUE THREAD

**Issue by blurayne** [erebe/wstunnel#313]
## Describe the feature

While it is possible to try random ports on for forwarding it would be great if the server determines what ports are free and returns me info about it.

## Describe the reason for such feature

I want to connect local debug services (running in cicd pipelines) to be accessible via a proxy 

## Describe alternatives you've considered

Try with random ports until I get a connection.

**Comment by erebe** [comment]
Hello,

I am not sure to understand where you want the random port.
Is it when starting wstunnel server ? To avoid specifying the listening port of the server ?
Is it when doing forwarding client side with -L ?
reverse tunnel ?

**Comment by christoph-kluge** [comment]
@erebe I think I have a similar case.. Let me know when I should open up a new issue. I'm happy to do so 👍 

I'm building up a fleet of IoT devices. So the `wstunnel client` as systemd-service is "more or less" hardcoded on each device. 

I would like to tunnel into 1:n devices in order to debug things. There is a chance that I need to connect to more than one device at the same time in order to compare behaviors, which would lead to a port collision on the server. Example:

```
iot-device-1 % wstunnel client -R 'tcp://8022:127.0.0.1:22' wss://example.net
iot-device-2 % wstunnel client -R 'tcp://8022:127.0.0.1:22' wss://example.net 
// wstunnel server logs the following when iot-device-2 tries to establish a connection
// errors: wstunnel::tunnel::server: Rejecting connection with bad upgrade request: Cannot create TCP server 127.0.0.1:8022 /v1/events
```

What I am looking for is something like below which will eliminate the remote-port detection out of the equation and only define the "local" port on the device.

```
iot-device-1 % wstunnel client -R 'tcp://{RANDOM_SERVER_PORT}:127.0.0.1:22' wss://example.net
iot-device-2 % wstunnel client -R 'tcp://{RANDOM_SERVER_PORT}:127.0.0.1:22' wss://example.net
```

Is this achievable with `wstunnel`. Did I miss some parts of the documentation?

**Comment by erebe** [comment]
If you set `0`, you will end-up with a random port server side.

The other alternative is to use the port-mapping feature.
There is the port-mapping feature that does that 
https://github.com/erebe/wstunnel/blob/main/restrictions.yaml#L54

It was introduced for iot devices. Each iot client has a specific path prefix (or with mTLS) and you create a restriction config for each devices and port-mapp to something specfic

**Comment by pavel-orlov** [comment]
> If you set `0` for the server port, you will end-up with a random port server side.

How can a client get the ephemeral server port?

**Comment by erebe** [comment]
hey, don't think there is a way for the client to get it. You will get 0 in the log trace

**Comment by christoph-kluge** [comment]
You might send the port back to the client based on the server-logs.

Client (192.168.65.1)
```
% wstunnel client --log-lvl=info -R 'tcp://0:127.0.0.1:1234' ws://127.0.0.1:8080
[...] INFO wstunnel::tcp: Opening TCP connection to 127.0.0.1:8080
```

Server
```
[...] INFO tunnel{peer="[::ffff:192.168.65.1]:22867" id="[...]" remote="127.0.0.1:0"}: wstunnel::protocols::tcp::server: Starting TCP server listening cnx on 127.0.0.1:0
```

`peer="[::ffff:192.168.65.1]:22867"` gives you the required information.

**Comment by pavel-orlov** [comment]
Hi, @erebe 
> hey, don't think there is a way for the client to get it. You will get 0 in the log trace

What if we find a random port e.g.:
```
LocalProtocol::ReverseTcp => {
                static SERVERS: LazyLock<ReverseTunnelServer<TcpTunnelListener>> =
                    LazyLock::new(ReverseTunnelServer::new);

                let remote_port = if remote.port == 0 {
                    find_ephemeral_port(remote.host.clone())
                } else {
                    find_mapped_port(remote.port, restriction)
                };
                let local_srv = (remote.host, remote_port);
                let bind = try_to_sock_addr(local_srv.clone())?;
                let listening_server = async { TcpTunnelListener::new(bind, local_srv.clone(), false).await };
                let ((local_rx, local_tx), remote) = SERVERS.run_listening_server(BindAddr::Socket(bind), listening_server).await?;
                Ok((remote, Box::pin(local_rx), Box::pin(local_tx)))
            }
```

Is there a way to send it back to the client?
