### ISSUE TITLE
Need help for android

### ISSUE THREAD

**Issue by mnaveedpaki** [erebe/wstunnel#316]
## Describe the goal
I want to implement wstunnel for wireguard on android.
I am developing wireguard vpn app on android studio but it is not working in some countries due to their firewall.

## Describe what does not work
I have compiled binary files for all android architecture but every time it shows an error segmentation fault
Maybe I am not following the correct way. If there is any guide available please mention it.

## Desktop (please complete the following information):
 - OS: android

**Comment by erebe** [comment]
You may want to check this issue https://github.com/erebe/wstunnel/issues/292#issuecomment-2211833902

The android binary should be packageable inside an android app.

Beside that i can't help you much, don't have experience in android développement

**Comment by mnaveedpaki** [comment]
I have tried wstunnel on termux, it works on termux but there is no implementation guide available for android studio or how to implement in android app.

**Comment by mnaveedpaki** [comment]
> You may want to check this issue [#292 (comment)](https://github.com/erebe/wstunnel/issues/292#issuecomment-2211833902)
> 
> The android binary should be packageable inside an android app.
> 
> Beside that i can't help you much, don't have experience in android développement

can you just guide me how can i generate .so files?

**Comment by erebe** [comment]
I don't think you can generate a .so out the project, because there is no library declared.
I should refacto the project to split the code between a lib and a binary using thid lib, for it to be possible.

So my take is that you only can if you invoke the binqry/exec it from your app.

But again, i am no an droid developper so take it with a grain of salt.

**Comment by mnaveedpaki** [comment]
i can not invoke binqry/exec from the app because android security does not allow to execute binqry/exec directly.
You need .so shared files.

**Comment by mnaveedpaki** [comment]
On server side it is implemented. is there any way how can i implement on android?
can i use websocket?

**Comment by mnaveedpaki** [comment]
I did it myself.
Thanks for this awesome project
