### ISSUE TITLE
Binding Apache with wstunnel server

### ISSUE THREAD

**Issue by michabbs** [erebe/wstunnel#317]
Could you please provide example apache configuration which would proxy chosen url to wstunnel?

## Describe the goal
I would like to share wstunnel server with regular apache server on the same 443 port. This way the same public ip could be used to serve normal web services as well as my secret tunnel endpoint.

## Describe what does not work
I am unable to forward connection from apache to wstunnel. :-(

## Describe your wstunnel setup
I started server this way:
`wstunnel server --restrict-to localhost:22 ws://127.0.0.1:8080`

I tried to deal with apache more or less this way:
```
<VirtualHost *:443>
 ServerName my.server.name
 #(ssl certs from letsencrypt here)
 ProxyPass /ws ws://127.0.0.1:8080/
</VirtualHost>
```
And finally I tried to run client this way:
`wstunnel client -L tcp://9999:127.0.0.1:22 wss://my.server.name/ws`

The result looks so:
```
2024-07-13T18:22:16.723990Z  INFO wstunnel::tcp: Starting TCP server listening cnx on 127.0.0.1:9999
2024-07-13T18:22:19.058559Z  INFO wstunnel::tcp: Opening TCP connection to xxx
2024-07-13T18:22:19.090743Z  INFO wstunnel::tls: Doing TLS handshake using SNI DnsName("xxx") with the server xxx
2024-07-13T18:22:19.159481Z ERROR tunnel{id="xxx" remote="127.0.0.1:22"}: wstunnel::tunnel::client: failed to do websocket handshake with the server wss://xxx
```

## Desktop (please complete the following information):
Server: Debian Bookworm
Client: MacOS

**Comment by erebe** [comment]
try with option `--http-upgrade-path-prefix` 
```
wstunnel client -L tcp://9999:127.0.0.1:22 -P ws  wss://my.server.name
```

**Comment by michabbs** [comment]
> ```
> wstunnel client -L tcp://9999:127.0.0.1:22 -P ws  wss://my.server.name
> ```

Master, it's alive! :-)
