### ISSUE TITLE
I want to add static route in android

### ISSUE THREAD

**Issue by mnaveedpaki** [erebe/wstunnel#319]
## Describe the goal
I want to add static route in android

## Describe what does not work
i have compiled .so files for android anf after running it is showing
Starting UDP server listening cnx on 127.0.0.1:51820 with cnx timeout of 0s

But i can not not add static rout like sudo ip route add ip.of.my.server.com dev eth0 via 192.168.0.1
because it require ROOT access and i am developing app to distribute on play store for public use.

## Describe your wstunnel setup
wstunnel client -L 'udp://51820:127.0.0.1:51820?timeout_sec=0' wss://my_server:443/

## Desktop (please complete the following information):
 - OS: Android

**Comment by erebe** [comment]
You should look into wireguard app to know how they do it. Must have some android API that make it possible without being root.

**Comment by erebe** [comment]
https://developer.android.com/reference/android/net/VpnService.Builder#addRoute(java.net.InetAddress,%20int)

**Comment by mnaveedpaki** [comment]
> https://developer.android.com/reference/android/net/VpnService.Builder#addRoute(java.net.InetAddress,%20int)

This is not working because of Wireguard already using vpnservice class.

**Comment by mnaveedpaki** [comment]
is there any other way like if i use HTTPS or Socks5???

**Comment by maytom2016** [comment]
it seems wstunnel is work on Application layer.all of route is controlled by wireguard.why you have to add static route？if you want to add a route,you should change wireguard config file AllowedIPs option.

> is there any other way like if i use HTTPS or Socks5, So i don't have to use static route????
