### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by maxchendt** [erebe/wstunnel#32]
It seems that `wstunnel` does not support IPv6 yet

    ./wstunnel_linux_x64 -D [2001:da8:e::1:6]:24080 ws://127.0.0.1:8080

with errror
```
wstunnel_linux_x64: Invalid tunneling information `[2001:da8:e::1:6]:24080:127.0.0.1:1212`, please use format [BIND:]PORT:HOST:PORT
CallStack (from HasCallStack):
  error, called at app/Main.hs:97:35 in main:Main
```

I try using host (set in dns, or in etc\hosts)

    ./wstunnel_linux_x64 -D ws.uk.to:24080 ws://127.0.0.1:8080

then not be resolved
```
Starting socks5 proxy ServerSettings {listenOn = 24080, bindOn = "ws.uk.to"}
wstunnel_linux_x64: Network.Socket.getAddrInfo: does not exist (Name does not resolve)
```

**Comment by erebe** [comment]
Hello,

Sorry for the delay.
Regarding your issue, wstunnel should be able to work with IPv6. it is just that my command line parsing that is shitty.
I will take a look this weekend and let you know about the otucome

**Comment by erebe** [comment]
Hello,
I made some fixes, would you mind trying this release ? https://github.com/erebe/wstunnel/releases/download/%2332/wstunnel

**Comment by maxchendt** [comment]
Thanks so much!, it works now, both on server and client side.

**Comment by erebe** [comment]
Awesome thanks, I am going to make a new release so

**Comment by erebe** [comment]
https://github.com/erebe/wstunnel/releases/tag/v3.0
