### ISSUE TITLE
panic (core dumped) (version 9.7.3)

### ISSUE THREAD

**Issue by mmikel** [erebe/wstunnel#320]
~# /tmp/wstunnel -V
wstunnel 9.7.3

~# RUST_BACKTRACE=full /tmp/wstunnel server ws://0.0.0.0:8086
thread 'main' panicked at src/main.rs:786:10:
called `Result::unwrap()` on an `Err` value: Os { code: 99, kind: AddrNotAvailable, message: "Address not available" }
stack backtrace:
   0:     0x7c87c452a60e - <unknown>
   1:     0x7c87c42078fc - <unknown>
   2:     0x7c87c44fffe2 - <unknown>
   3:     0x7c87c452c06f - <unknown>
   4:     0x7c87c452b878 - <unknown>
   5:     0x7c87c452c950 - <unknown>
   6:     0x7c87c452c3c0 - <unknown>
   7:     0x7c87c452c316 - <unknown>
   8:     0x7c87c452c303 - <unknown>
   9:     0x7c87c3eb5a44 - <unknown>
  10:     0x7c87c3eb5e62 - <unknown>
  11:     0x7c87c4178c73 - <unknown>
  12:     0x7c87c416d05e - <unknown>
  13:     0x7c87c3fe3a43 - <unknown>
  14:     0x7c87c419f735 - <unknown>
Aborted (core dumped)

error introduced in version 9.7.3, 9.7.2 works well...

**Comment by erebe** [comment]
indeed, forgot to delete some code...
Going to fix

**Comment by erebe** [comment]
Should be fixed with https://github.com/erebe/wstunnel/releases/tag/v9.7.4
let me know if it is not ther case

**Comment by mmikel** [comment]
9.7.4 works fine, thx!

**Comment by erebe** [comment]
perfect, thank you :pray:
