### ISSUE TITLE
How Add login/password support??

### ISSUE THREAD

**Issue by yymk158** [erebe/wstunnel#322]
## Describe the goal
I need the server to verify the username and password of the client.
Prevent anyone from being able to connect to my server

## Describe what does not work
Unable to connect

## Describe your wstunnel setup

wstunnel server wss://0.0.0.0:xxxx?login=abcd1234&password=aaaabbbb
wstunnel client -L socks5://127.0.0.1:1080?login=abcd1234&password=aaaabbbb https://server ip:xxxx

**Comment by dobelachaos** [comment]
You need to add quotation marks, like this:
wstunnel client -L "socks5://127.0.0.1:1080?login=abcd1234&password=aaaabbbb" https://server/ ip:xxxx

**Comment by yymk158** [comment]
wstunnel server "wss://0.0.0.0:xxxx?login=abcd1234&password=aaaabbbb"

server Is that correct?

Is it " or '   ?

**Comment by erebe** [comment]
https://github.com/erebe/wstunnel?tab=readme-ov-file#how-to-secure-the-access-of-your-wstunnel-server-

**Comment by yymk158** [comment]
> https://github.com/erebe/wstunnel?tab=readme-ov-file#how-to-secure-the-access-of-your-wstunnel-server-

Because I don't understand the description above the content, I can't use it correctly, can you explain the description in more detail?

**Comment by yymk158** [comment]
I'm just a regular user, I'm not a programmer, I can't read a lot of descriptions, I hope I can get help
