### ISSUE TITLE
"Unix socket is not available for non Unix platform", error from a Windows client trying to create -R connection at Linux server.

### ISSUE THREAD

**Issue by yuan-thomas** [erebe/wstunnel#333]
## Describe the bug
This should be a simple description:
I am trying to establish a reverse connection by creating a unix socket at the server (Linux). My client is Windows.

When I run client command:
wstunnel client -R unix:///var/tmp/test.sock:www.google.com:80 wss://wstunnel.myserver.com

I get this error:
thread 'main' panicked at src\main.rs:1084:25:
Unix socket is not available for non Unix platform

Whereas I get that Unix Socket isn't available under Windows, it's probably not applicable because the socket will be created at server side.

## To Reproduce
wstunnel client -R unix:///var/tmp/test.sock:www.google.com:80 wss://wstunnel.myserver.com

## Your wstunnel setup
Paste your logs of wstunnel, started with `--log-lvl=DEBUG`, and with the `command line used`
 - client
 - server

## Desktop (please complete the following information):

**Additional context**

**Comment by erebe** [comment]
Indeed going to fix it for next release

**Comment by erebe** [comment]
it is fixed in v10.0 release

**Comment by yuan-thomas** [comment]
v10.0, what an honor! Thank you.
