### ISSUE TITLE
timeout `header_read_timeout` set, but no timer set

### ISSUE THREAD

**Issue by Yaya48** [erebe/wstunnel#335]
![image](https://github.com/user-attachments/assets/ad1c12cd-f4e2-45d8-aa83-ef6d6415eb07)

wstunnel panic when the client is trying to connect both client & server are updated to latest v10 update

**Comment by erebe** [comment]
It will be fixed in a few minutes by the new release sorry :x

**Comment by erebe** [comment]
It is fixed in the latest release v10.0.1, sorry about that again
