### ISSUE TITLE
wstunnel crashes with curl request

### ISSUE THREAD

**Issue by Abh15h3k** [erebe/wstunnel#344]
## Describe the bug
I use curl to quickly check if the "server" is up and running with the correct certificate.
in version 10.1.0 wstunnel server panics when i initiate a curl request.

## To Reproduce
- download / build wstunnel 10.1.0
- run `wstunnel server 'wss://[::]:5443'`
- on another terminal run `curl https://localhost:5443'` (server doesn't crash, curl gives certificate error)
- run `curl https://localhost:5443' -k` (server crashes)

## Expected behavior
curl should fail with "Invalid upgrade request" and same should be printed in wstunnel server logs as a warning. server should remain up and running for further connections

## Your wstunnel setup
Paste your logs of wstunnel, started with `--log-lvl=DEBUG`, and with the `wstunnel server 'wss://[::]:5443`
 - server [wstunnel-server.log](https://github.com/user-attachments/files/16834670/wstunnel-server.log)

## Desktop (please complete the following information):
 - OS: Archlinux (Also tested same with server running on Ubuntu 22.04)
 - Version: Rolling

**Additional context**
Tested with included ssl certificate and certificate from lets encrypt.
Issue is only happening when running with `wss://` and not with `ws://` (as in, with ws:// the server gives invalid request and does not crash)

**Comment by erebe** [comment]
Indeed thanks for reporting it.
I am going to fix it and release a new version today.

**Comment by erebe** [comment]
Should be fixed in the latest release https://github.com/erebe/wstunnel/releases/tag/v10.1.1
