### ISSUE TITLE
Tokio Panic

### ISSUE THREAD

**Issue by Draconich** [erebe/wstunnel#348]
[wstunnel_logs.txt](https://github.com/user-attachments/files/16986582/wstunnel_logs.txt)
## Describe the bug
Wstunnel crashes with a frequency about once a day with this error 
`thread 'tokio-runtime-worker' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.4.1/src/common/time.rs:37:17: `

There is also constant spamming of this error which i don't know if relevant or not.
`Error while upgrading cnx: hyper::Error(HeaderTimeout)`
## To Reproduce

Run /usr/local/bin/wstunnel server --restrict-config /etc/restrictions.yaml  wss://[::]:5555  for about a day.

## Expected behavior
Not to panic.

## Your wstunnel setup
Added log snippet as a file. It's running  without a reverse proxy and clients that are connecting to it go through a MITM squid proxy.

## Desktop (please complete the following information):
 It's running on 32-bit Ubuntu 18.04.
Wstunnel v10.1.0
**Additional context**
If it's not enough i can switch to DEBUG log level or run with RUST_BACKTRACE=1 -  i just only discovered it by looking at systemctl status wstunnel.service and seeing a 1 day uptime.

**Comment by erebe** [comment]
Hello,

Please use the latest version. It has been fixed in v10.1.1 https://github.com/erebe/wstunnel/releases/tag/v10.1.1
