### ISSUE TITLE
Version 3 stable release date

### ISSUE THREAD

**Issue by Hitamashi** [erebe/wstunnel#35]
Hello,

I am glad that wstunnel have new features and I really love to use the `-L` parameters to group severals  wstunnel process. But right now, it's still a pre-release version.
May I know that when will we have the stable version?

Thank you

**Comment by erebe** [comment]
Hello,
The version 3.0 is stable, it is just that i don't have all the target build that i would like to do à release (macos and some arm) and i don't know if i will, manage to get them as some hardware is quite hard to get nowadays.

So feel free to use the 3.0, Nothing more is planned for it.

P. S: i am in vacation for 3 weeks

**Comment by Hitamashi** [comment]
Thank you for the info 
Enjoy your vacation!
