### ISSUE TITLE
Server logged message line grows in length with each denied connection attempt from a given client

### ISSUE THREAD

**Issue by JamesTGrant** [erebe/wstunnel#355]
When a client attempts to connect with an incorrect password, the cooresponding server log message grows in length with each repeated report of the incident. 
I think this is related or the same as the following issue you previously fixed in the client: https://github.com/erebe/wstunnel/issues/242

tested using v9.7.4 and v10.1.1

Please see example log output attached:
[growing.txt](https://github.com/user-attachments/files/17061918/growing.txt)

(the restrictions file and functionality is awesome by the way)

**Comment by erebe** [comment]
Hello,
Thanks for reporting, I am going to fix it when I come back from vacation (2 weeks)

**Comment by erebe** [comment]
Shoud be fixed in next release, you can give it a try in this pre-release https://github.com/erebe/wstunnel/releases/tag/v10.1.2-rc1

**Comment by erebe** [comment]
Made a proper release https://github.com/erebe/wstunnel/releases/tag/v10.1.2

Let me know if it is ok.

**Comment by JamesTGrant** [comment]
Welcome back, hope the holiday was ace!
I will test this in the next couple of hours and report back this morning.

**Comment by JamesTGrant** [comment]
Tested with v10.1.2 and I confirm that this is FIXED! Lovely, thank you.
