### ISSUE TITLE
SSL handshake error with server behind nginx

### ISSUE THREAD

**Issue by Hitamashi** [erebe/wstunnel#37]
## Description
I have problem with the wstunnel v3 (linux) causing my nginx saying
```
client timed out (110: Connection timed out) while SSL handshaking
```

On previous versions, everything is ok. Even on your recent [build](https://github.com/erebe/wstunnel/runs/377533985), the binary worked for me.   

## How to reproduce
Here is my simple topology:
```
client <=> nginx <=> server
```
### Client side
```
wstunnel -L 127.0.0.1:4505:my_remote:4505 wss://mynginx
```

### Server side
```
wstunnel --server ws://0.0.0.0:4515 -r 127.0.0.1:4505
# Service is listening to port 4505 on server side
```

### nginx
```
server {
    listen  443 ssl;
    tcp_nopush on;
    tcp_nodelay on;
   ... some ssl config ...

    location ~ ^/wstunnel/tcp/my_remote/4505 {
        rewrite ^ /tcp/127.0.0.1/4505 break;
        proxy_pass              http://myserver:4515;
        proxy_next_upstream     off;
        proxy_http_version      1.1;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Connection "upgrade";
        proxy_send_timeout      5m;
        proxy_read_timeout      5m;
    }
```

I try to check the changes from the working build 39b37f0 with the latest release [here](https://github.com/erebe/wstunnel/compare/39b37f0...d3a8db6). It seems that you add some features for SO_MARK.
I have no idea about Haskell so could you please check it for me?

For now, I am using the binary from this build: https://github.com/erebe/wstunnel/runs/377533985

**Comment by sio2sio2** [comment]
I don't know if it's related (I think so), but v3.0 doens't work even without nginx.

## Server side

~~~
$ netcat -l -p 11111
$ wstunnel -v --server ws://0.0.0.0:8080
~~~

## Client side

~~~
$ wstunnel -v -L stdio:127.0.0.1:11111 ws:/192.168.0.14:8080
~~~

With v2 I can see "CONNECTING to 127.0.0.1:11111" in server side and it works, with v3.0 I don't

**Comment by erebe** [comment]
Hello,

It is indeed due to the last change with SO_MARK, you need to run wstunnel as root or it will crash the current thread silently. For more explanation see the commit message of the fix 5e1b790

I am in vacation for a few weeks, if you can try out the latest build https://github.com/erebe/wstunnel/runs/461980987?check_suite_focus=true and let me know if it solve the issue for you, I would be glad.

Cheers :)

**Comment by sio2sio2** [comment]
Thanks.

The lastest artifact doesn't work even as root. I've watched the outgoing packets from client with tcpdump and none goes out.

## Server side (192.168.0.14)

~~~
# wstunnel3+ -v --server ws://0.0.0.0
~~~

and

~~~~
$ netcat -l -p 1234
~~~~

## Client side (192.168.0.20)

~~~
# wstunnel3+  -vL stdio:127.0.0.1:1234 ws://192.168.0.14
~~~

and 

~~~
# tcpdump -ni eth0 tcp port 80 and host 192.168.0.14
~~~

Instead:

~~~
# wstunnel2  -vL stdio:127.0.0.1:1234 ws://192.168.0.14
~~~

if's work fine.

**Comment by Hitamashi** [comment]
@erebe Sorry to disturb your vacation.
The the binary in the latest artifact work for me but I introduced another problem about the socket is not closed.
When my client disconnected, the server still hold multiple connections with status `CLOSE_WAIT` and it somehow make the cpu load to 100% on server side. Maybe we have leaking sockets?
I will do more test and tell you later

**Comment by Hitamashi** [comment]
For CPU problem: https://github.com/erebe/wstunnel/issues/38

@sio2sio2 I think you need to open a new issue about stdio support.
I did some tests with and without nginx and it worked well for regular usage.

**Comment by erebe** [comment]
Closing as the original issue is fixed.
Please open a new issue for the stdio please @sio2sio2 
Haven't seen any obvious also as @Hitamashi with it
