### ISSUE TITLE
How to create tunnel?

### ISSUE THREAD

**Issue by OlegVladimirov** [erebe/wstunnel#373]
## Describe the goal
I whant to get local socks using public credentials

## Describe what does not work
I'm get SSH Websocket parameters from public provider (for example [SSH Websocket](https://sshocean.com/). Here it's present:
```
Server: fi2.wstunnel.site
Username: sshocean-name777
Password: ********
Protocol: SSH Websocket
Port:
  - 80, 8080, 8880, 2052, 2082, 2086, 2095
Port SSL/TLS:
  - 443, 2053, 2083, 2087, 2096, 8443
UDPGW:
  - 7200, 7300   
Created: 7 Nov 2024
Expired: 14 Nov 2024
wildcard domain format *.fi2.wstunnel.site
example: cloudflare.com.fi2.wstunnel.site
-----------------------
COPY PAYLOAD (HTTP):    GET / HTTP/1.1[crlf]Host: fi2.wstunnel.site[crlf]Upgrade: websocket[crlf][crlf]
COPY PAYLOAD (SSL/TLS): GET wss://SNI_bug_host/ HTTP/1.1[crlf]Host: fi2.wstunnel.site[crlf]Upgrade: Websocket[crlf]Connection: Keep-Alive[crlf][crlf]
```
I have Ubuntu and success download binary of wstunnel (wstunnel_10.1.5_linux_amd64). Now unsuccessful try to connect to this server:
```
./wstunnel client -L tcp://9999:127.0.0.1:22 wss://fi2.wstunnel.site:443
ssh -p 9999 -N -D 43765 sshocean-name777@127.0.0.1


# or
./wstunnel client -L socks5://127.0.0.1:55522 wss://fi2.wstunnel.site:443
ssh -p 55522 -N -D 43765 sshocean-name777@127.0.0.1
```
Bouth wrong. So, my question is - how to connect to SSH Websocket to get local socks5 proxy?

## Describe your wstunnel setup
Tryed:
./wstunnel client -L tcp://9999:127.0.0.1:22 wss://fi2.wstunnel.site:443
./wstunnel client -L socks5://127.0.0.1:55522 wss://fi2.wstunnel.site:443
what's rigtht syntax&

## Desktop (please complete the following information):
 - OS: Ubuntu
 - Version 22

**Comment by erebe** [comment]
You can take a look at https://github.com/erebe/wstunnel?tab=readme-ov-file#ssh for an example
