### ISSUE TITLE
(v3.0)High CPU utilization.

### ISSUE THREAD

**Issue by Thnineer** [erebe/wstunnel#38]
Server:
wstunnel-linux --server ws://0.0.0.0:8080 -r 127.0.0.1:2333
(127.0.0.1:2333 => caddy web server,convert ws to wss)

Client:
wstunnel-linux -L 8081:127.0.0.1:2333 wss://remote

Run command:
curl 127.0.0.1:8081
then
the wstunnel-linux process of the server use almost 100% of the CPU.
![image_6.png](https://i.loli.net/2020/02/24/cVsrfNkCBu2yTSl.png)

This problem will not repetition in v2.0.

**Comment by erebe** [comment]
Can you check the lastest artifact https://github.com/erebe/wstunnel/runs/465284666?check_suite_focus=true ?
It should fix the regression

**Comment by Hitamashi** [comment]
👍  I have done some tests on my side and the cpu usage is back to normal in this version

**Comment by erebe** [comment]
:+1:
