### ISSUE TITLE
Remote-to-local command line parsing is broken in 10.1.7

### ISSUE THREAD

**Issue by rayslava** [erebe/wstunnel#386]
## Describe the bug
```
wstunnel client -R 'tcp://127.0.0.1:443:127.0.0.1:443' wss://the_remote_host:1111
error: invalid value 'tcp://127.0.0.1:443:127.0.0.1:443' for '--remote-to-local <{tcp,udp,socks5,unix}://[BIND:]PORT:HOST:PORT>': cannot parse remote port from 127.0.0.1:443
```

## To Reproduce
Try to run the remote-to-local tunnel

## Expected behavior
Tunnel works

## Your wstunnel setup
Paste your logs of wstunnel, started with `--log-lvl=DEBUG`, and with the `command line used`
 - client 10.1.7
 - server 10.1.6

## Desktop (please complete the following information):
 - OS: Gentoo
 - Version N/A

**Additional context**
Version 10.1.6 works as intended, 10.1.7 can't parse the command line

**Comment by erebe** [comment]
Hello,

Thanks for reporting, it should be fixed in new release https://github.com/erebe/wstunnel/releases/tag/v10.1.8

Let me know if it is not the case

**Comment by rayslava** [comment]
Confirming, 10.1.8 works.
Thank you!
