### ISSUE TITLE
stdio support is broken

### ISSUE THREAD

**Issue by sio2sio2** [erebe/wstunnel#39]
At least as of version 3 stdio support is broken:

### Server

~~~
wstunnel -v --server ws://0.0.0.0
netcat -l -p 1234
~~~

### Client

~~~
wstunnel  -vL stdio:127.0.0.1:1234 ws://192.168.0.14
~~~

**Comment by erebe** [comment]
Should be fixed with the latest artifact https://github.com/erebe/wstunnel/runs/465805274
Can you let me know if it is ok for you ?

**Comment by sio2sio2** [comment]
It' works for me. Thanks.

**Comment by erebe** [comment]
Thanks :)
Sorry about that, I have made somes changes for a guys that was willing to pay to transform a bit wstunnel for his usage, and I mistakenly commited a bit of his changes into the master branch
