### ISSUE TITLE
Udp not working

### ISSUE THREAD

**Issue by sgsdxzy** [erebe/wstunnel#40]
Using version 2.0
On the Linux server side: `wstunnel --server ws://0.0.0.0:10001`
On the Windows client side: `wstunnel.exe -u ws://name.domain -D 1080`
Now tcp traffic works fine, but udp doesn't work.
On the server side, there is a lot of logs:
`CONNECTING to 0.0.0.0:0
wstunnel: Network.Socket.connect: <socket: 12>: does not exist (Connection refused)`

**Comment by erebe** [comment]
Hello,

Sadly UDP mode is not working with -D, you can only use it with -L command.

**Comment by sgsdxzy** [comment]
I want to setup a socks5 proxy that on the client side it listens on 1080 and accept both tcp and udp. And all traffic is forwarded to server websocket.
Programs that use both tcp and udp can use this socks proxy to access internet.
Is this possible?

**Comment by erebe** [comment]
Socks5 proxy will only be able to listen for TCP connections. So you will not be able to forward udp traffic with it
