### ISSUE TITLE
Show source ip in logging

### ISSUE THREAD

**Issue by thehotery** [erebe/wstunnel#41]
It is possible to add client's source ip in log? Now even with verbose logging enabled (-v) its shows only
  wstunnel[16586]: CONNECTING to 127.0.0.1:22
  wstunnel[16586]: CLOSE connection to 127.0.0.1:22

I'm running wstunnel server behind cloud serviice (which send x-forwarded-for with real ip) but with direct connection all the same. And ssh or other service "in the end" only see 127.0.0.1 so no ip logging at all.

**Comment by erebe** [comment]
You can try the binaries from this run/artifacts and let me know the outcome ?
https://github.com/erebe/wstunnel/runs/619748369

**Comment by erebe** [comment]
in release 3.0
