### ISSUE TITLE
Publish to hackage

### ISSUE THREAD

**Issue by poscat0x04** [erebe/wstunnel#44]
Great work! Would you mind publishing this package to hackage?

**Comment by erebe** [comment]
Done https://hackage.haskell.org/package/wstunnel

**Comment by hmenke** [comment]
Can you please publish v3.1 to hackage as well?

The hackage page also has some typos, because many of the template values were not replaced in the cabal file:

https://github.com/erebe/wstunnel/blob/e9b1a53d3d2c0b75a8b35b616b350643f5880e90/wstunnel.cabal#L3-L10

**Comment by erebe** [comment]
It is done. Let me know if it is not ok

**Comment by hmenke** [comment]
Can you please publish v4.0 on hackage? It's still on 0.3.1.0 over there.

**Comment by erebe** [comment]
Done, for latest version 4.1.0 https://hackage.haskell.org/package/wstunnel
