### ISSUE TITLE
wstunnel needs version bounds

### ISSUE THREAD

**Issue by rwlock404** [erebe/wstunnel#45]
As I just reported over at https://github.com/haskell-infra/hackage-trustees/issues/265 I wasn't able to install `wstunnel`. [I was instructed](https://github.com/haskell-infra/hackage-trustees/issues/265#issuecomment-623982181) to file the issue upstream here.

It is my understanding that the `wstunnel-0.3.0.0` release on Hackage is broken because of missing version bounds. Can you add the missing bounds?

**Comment by erebe** [comment]
Hello,
Yes sorry fixing that

**Comment by erebe** [comment]
Should be better.
By the way what wstunnel is doing on haskell-infra/hackage-trustees ?

**Comment by rwlock404** [comment]
`cabal install wstunnel-0.3.0.0` still fails for me :-(

**Comment by erebe** [comment]
What error do you have ?

**Comment by rwlock404** [comment]
Same as previously. Also https://hackage.haskell.org/package/wstunnel-0.3.0.0/dependencies still seems to be missing most bounds?

**Comment by erebe** [comment]
I can't reupload the same version, you need to use the latest one https://hackage.haskell.org/package/wstunnel-0.3.0.1/dependencies

**Comment by rwlock404** [comment]
I get this  error when I try to `cabal install wstools-0.3.0.1`

```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] next goal: wstunnel (user goal)
[__0] rejecting: wstunnel-0.3.0.0, wstunnel-0.1.0.0
(constraint from user target requires ==0.3.0.1)
[__0] fail (backjumping, conflict set: wstunnel)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: wstunnel
```

**Comment by erebe** [comment]
you need to do a cabal update in order to get the version wstunnel-0.3.0.1

**Comment by rwlock404** [comment]
D'oh... right! Now it seems to install. Thanks!

BTW why are there still many bounds showing as missing at https://hackage.haskell.org/package/wstunnel-0.3.0.1/dependencies ?

**Comment by erebe** [comment]
They are not hard requirement (i hope) as long as network and base are satisfied
