### ISSUE TITLE
wstunnel on android.

### ISSUE THREAD

**Issue by ingnelson** [erebe/wstunnel#49]
Hello sir.

Question #1: 
How can i use wstunnel on my android cellphone as a client to use it as a VPN to tunnel all the connection ?
i just install wstunnel on my UBUNTU vps as a server.

Question #2: 
I am behind a firewall and the firewall only let pass packet no more to 2000 bytes .

is it possible to add a option on the server to send the packet via "segment packet" , so the server should send the packet no more than 2000 bytes for example, Like  " data chunk over multiple packet"?  .
 

i will wait your answer. i really need your opinions.

**Comment by erebe** [comment]
for 1, you need to root your phone. As it depends on of your phone and it is way beyond the scope of this project, you are on your own to figure out about how to do that.

for 2, you can change the MTU on your network card (server side), the OS will fragment the message with at max MTU size
