### ISSUE TITLE
Support Basic Auth

### ISSUE THREAD

**Issue by AndreasAmMueller** [erebe/wstunnel#50]
I'm using your wstunnel behind NginX as Proxy. The `upgradePathPrefix` makes it capable to run next to a deployed website.

But I additinally want to secure this websocket by a basic authentication.    
Therefore I thought it would be great to support something like `wstunnel -L 1234:remote.tld:4321 --upgradePathPrefix=/some/subpath wss://<user>:<pass>@domain.tld`

Supporting `<user>:<pass>@` in the connection string would be great!

Current behaviour: The parser detects `<pass>@...` as port - well, and fails^^

**Comment by erebe** [comment]
Hello,
For this kind of thing it is easier to use a reverseProxy in front of wstunnel (i.e: nginx)
There is an example of setup in the readme, adding basic auth is just a few more lines 
https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

**Comment by contrun** [comment]
I think the OP meant that when the user specify the server url `wss://<user>:<pass>@domain.tld`. `wstunnel` should try to connect the server `domain.tld` with basic auth user `<user>` and basic auth password `<pass>`. It is not setup up a server which supports basic auth, which is fairly trivial with a reverse proxy. The thing is that we need the client `wstunnel` connect to the server with the given basic auth credentials.
