### ISSUE TITLE
Custom ws ping value

### ISSUE THREAD

**Issue by marty-macfly** [erebe/wstunnel#57]
Hello,

I'm doing a followup on issue #6 in most of case 30 seconds ping is enough but we have case where it's not do you think it can be possible to make it be override through an extra arguments on command line ? 

https://github.com/erebe/wstunnel/blob/093a01fa3a34eee5efd8f827900e64eab9d16c05/src/Tunnel.hs#L77

**Comment by erebe** [comment]
Hello,
I don't plan to make a new release of wstunnel soon, so if you are in a hurry you can fork the project and change the hardcoded value. The github CI will create you a new binary for linux in the artifacts.

**Comment by erebe** [comment]
Done in pre-release v3.1
https://github.com/erebe/wstunnel/releases/tag/v3.1
