### ISSUE TITLE
Does this work on FreeBSD

### ISSUE THREAD

**Issue by skanga** [erebe/wstunnel#58]
I did not find any binaries. And so I looked into the build from source option and got this ....

$ curl -sSL https://get.haskellstack.org/ | sh
Sorry, this installer does not support your operating system: FreeBSD.
See http://docs.haskellstack.org/en/stable/install_and_upgrade/

**Comment by erebe** [comment]
Stack dropped support for freebsd on recent version.
You can try this release https://github.com/commercialhaskell/stack/releases/tag/v2.1.3 and download stack for your arch

**Comment by Aster-the-Med-Stu** [comment]
For FreeBSD users, I would recommend [Go Simple Tunnel, or GOST by ginuerzh](https://github.com/ginuerzh/gost). It is written in Golang thus [having support for FreeBSD](https://github.com/ginuerzh/gost/releases/).

As the [English documentation is quite vague](https://github.com/ginuerzh/gost/blob/master/README_en.md), I would offer some examples for reference. More documentation is hosted on https://docs.ginuerzh.xyz/gost/ but **you have to understand Chinese!**

# Basics: Port Forwarding Over Plain WebSocket Using GOST

## TCP Port Forward Over Plain WebSocket

Say you are running a service at port 8000 on client, and you wish to forward it at port 80 on server thus the service could be accessed everywhere. Of course, WebSocket couldn't be used for forwarding UDP packets. **It's TCP stream!**

### On Client Side

```gost -L rtcp://:80/:8000 -F ws://[Server IP]:12345```

```-L``` flag tells GOST what to listen. rtcp here means TCP connection remotely on server at port 80 and ```-F``` flag tell GOST where should it send the data.

### On Server Side

```gost -L ws://:12345/```

## TCP and UDP Port Forward Over Plain WebSocket

As the old saying goes, where there is a need, there is a way. GOST does the trick of forwarding UDP packets by wrapping original packet in a SOCKS5 wrapper and then sending them through WebSocket.

### On Client Side

```gost -L rtcp://:80/:8000 rudp://:80/:8000 -F socks5+ws://[Server IP]:12345```

### On Server Side

```gost -L socks5+ws://:12345```

## Note: Connecting to Secure WebSocket with Sub Path

Maybe you wish to use Nginx, etc. for reverse proxying different services and set up secure WebSocket over TLS. You should already know how to correctly set up a reverse proxy for forwarding WebSocket with some sub path. Then you could tell client to connect using Secure WebSocket (wss://) by:

```gost -L rtcp://:80/:8000 rudp://:80/:8000 -F socks5+wss://[Server IP]:12345?path=/somepath```

# Advanced: More websocket configs for server side

On server side, some flags could be used for changing the websocket listener's behaviour. The schema is a little different according to what you wish to achieve.

## Plain WebSocket

```gost -L "ws://:8080?path=/ws&rbuf=4096&wbuf=4096&compression=false"```

Obviously, path is for the sub path, and compression is for whether enabling compression. Here, rbuf is for reading buffer size, and wbuf is for writing (sending) buffer size.

## Multiplexing

To enable multiplexing (GOST's own implementation? I'm not quite sure), change ws:// (wss://) for mws:// (mwss://) on both client and server.

Another tool that could be used for the same purpose is[ V2fly (Originally V2Ray)](https://www.v2fly.org/en_US/). Designed as a mechanism to bypass GFW (China Internet Censorship), it offers more protocols, like mKCP protocol for overcoming UDP QoS and mimic packets as WeChat video chatting data stream. But the config is in JSON and could be a headache for any newcomers.

Hope this could help you @skanga

**Comment by skanga** [comment]
@Aster-the-Med-Stu - Thank you so very much, this is great info. I will try it ...
