### ISSUE TITLE
CallStack error

### ISSUE THREAD

**Issue by dhensen** [erebe/wstunnel#60]
![2020-11-06-114608_883x747_scrot](https://user-images.githubusercontent.com/2786295/98357729-ea32ab00-2025-11eb-8fcc-4931c4d5a153.png)

I think screenshot says it all. From top to bottom:
- wstunnel server on `emilia`
- wstunnel client on `liekaliek`
- curl using the socks5 option via liekaliek wstunnel client

Version command seems to be broken (also tried with `-V`):
```
wstunnel --version
Use the websockets protocol to tunnel {TCP,UDP} traffic
wsTunnelClient <---> wsTunnelServer <---> RemoteHost
Use secure connection (wss://) to bypass proxies
```
```
sha256sum bin/wstunnel 
9443cd51230d53ce037e1f605584b1b656eec9ac9037ac0744102c408a9d6485  bin/wstunnel
```

This is the wstunnel binary from https://github.com/erebe/wstunnel/releases/download/v3.0/wstunnel-x64-linux.zip

**Comment by erebe** [comment]
You started the server in WSS mode (with TLS enabled) but your client is using plain WS without encryption.

Just start the client with wss://emilia

![image](https://user-images.githubusercontent.com/854278/98374633-40611780-2041-11eb-9b21-2dfdc9a1f17e.png)

**Comment by dhensen** [comment]
Makes sense, logical explanation, so I added an extra *s*, but I am getting the same error:
![2020-11-06-210949_913x1076_scrot](https://user-images.githubusercontent.com/2786295/98410205-82f01780-2074-11eb-8a28-38ab1425c867.png)

What else could it be?

**Comment by erebe** [comment]
Stange, can you send me a tcpdump  ?
'tcpdump -w wstunnel. pcap -i your_if_name' 

it seems something broken in socks5 decoding protocol

**Comment by dhensen** [comment]
Thanks for your time to investigate this!
[wstunnel.log](https://github.com/erebe/wstunnel/files/5504526/wstunnel.log)
(This is actually a .pcap file, but github wont allow that extension)

**Comment by erebe** [comment]
Ha sorry, can you retake the pcap but using **ws** instead of **wss** (for both server and client), I can't see the application data when it is encrypted over TLS ;x

**Comment by dhensen** [comment]
Haha, ofcourse.. did not think of this myself. Here it is: 
[wstunnel_no_tls.log](https://github.com/erebe/wstunnel/files/5504571/wstunnel_no_tls.log)

**Comment by erebe** [comment]
The new pcap only contains a DNS query ;o
Something missing  !

![image](https://user-images.githubusercontent.com/854278/98440988-87f8a980-20fc-11eb-9f25-178bf1ea58d6.png)

**Comment by dhensen** [comment]
[wstunnel_no_tls.log](https://github.com/erebe/wstunnel/files/5504725/wstunnel_no_tls.log)
Another one :+1: maybe I messed up... this one even contains a record from my washing machine, giving away my privacy :rofl:

**Comment by erebe** [comment]
Still not :x 
You need to take the capture from `lo` interface if you are doing it on the same machine 
One last time ? :disappointed:

**Comment by dhensen** [comment]
Ohhhh I was using enp3s0 and wlp2s0 on two different devices... :+1:  No worries, I can do this all week!
[wstunnel_no_tls_lo.log](https://github.com/erebe/wstunnel/files/5504740/wstunnel_no_tls_lo.log)

**Comment by erebe** [comment]
ha that because curl is trying to resolve the DNS name locally and that in your case you are under an IPv6 network.

![image](https://user-images.githubusercontent.com/854278/98442006-60a4db00-2102-11eb-8942-535d06dae748.png)

Wstunnel only support DOMAIN NAME or IPv4, as it is kind on flaky to try to connect to an IPv6 as your remote server may not support IPv6.

See this report for curl https://curl.haxx.se/mail/archive-2019-08/0017.html

To fix it, just use `curl -x socks5h:/`, note the **h** after the 5, curl will not resolve DNS name locally with it

**Comment by dhensen** [comment]
Oh my.. switched provider one week ago... ipv6 since then.
*h*  works, thanks a lot for all your time! I will play around with wstunnel this week  :+1:
