### ISSUE TITLE
v3.0 fails to launch due to dynamic linking (armv7h)

### ISSUE THREAD

**Issue by AlphaJack** [erebe/wstunnel#61]
I was going to update the binary, but I encountered the following error

```
./wstunnel: error while loading shared libraries: libffi.so.6: cannot open shared object file: No such file or directory
```
`file` returns this for v3.0 (17MB)
```
ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=7c4a688e5ee089fa20c79127662e82c37a947d07, stripped
```
and this for v2.0 (25MB)
```
ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, for GNU/Linux 3.2.0,  buildID[sha1]=fa32fe3994cc5db1e4f2c65579fd25766ff4cef7, stripped
```

Can you distribute a statically linked v3.0?  
Do the commands in `build_raspbian.sh` produce a statically or dynamically linked binary?

**Comment by erebe** [comment]
Which release are you using ?
I stopped doing armhf release as it was kind of impossible for me to find those kinds of processor available nowadays.

The build_raspbian.sh is going to produce a dynamic linked binary. But if you compile it on your machine it is going to work on it after that.

**Comment by AlphaJack** [comment]
I downloaded https://github.com/erebe/wstunnel/releases/download/v3.0/wstunnel-armv7l-raspbian-buster.tar.gz on my Raspberry Pi 2 running Arch Linux ARM

> The build_raspbian.sh is going to produce a dynamic linked binary. But if you compile it on your machine it is going to work on it after that.

Would it be possible to make it generate a statically linked binary like you did for v2.0? Otherwise I would need to recompile the program every time a library gets updated (e.g. I now have `libffi.so.7`, but the binary wants `libffi.so.6`). Redirecting `/usr/lib/libffi.so.6` to `/usr/lib/libffi.so` works as a temporary hack, but I wouldn't call it a long term solution

**Comment by erebe** [comment]
ha thar's why, the executable you downloaded is made for armhl (raspberry 4) not for armhf.

For the static binary question, i gave up on arm as I didn't managed to make one after several days spent on it. that's why 3.0 for arm has a release for Ubuntu and raspbian.

For your case, if it works by just changing the path you can use `chrpath` tool to avoid doing it each time.

**Comment by AlphaJack** [comment]
So, there is not a way to produce a statically linked armv7 binary like you did for x86_64?

The RPi 4 binary is running fine on my RPi 2, I just had to workaround the library file it depends on.
Didn't know about `chrpath`, but I'm encountering this error for v3:
```bash
$ chrpath -l /usr/bin/wstunnel3 
/usr/bin/wstunnel3: no rpath or runpath tag found.

# v2 for comparison
$ chrpath -l /usr/bin/wstunnel2
No dynamic section found.
found no dynamic section: Success
```
I read that `patchelf` can be used in these cases, may it will come in handy one day
