### ISSUE TITLE
Customize the TLS handshake

### ISSUE THREAD

**Issue by c1b3rd0rk** [erebe/wstunnel#62]
Some environments will raise an alert if your connection does not look like it is coming from the average client. I did not test wstunnel yet but I guess the TLS handshake will stick out. Would it be possible to customize the handshake in order to prevent fingerprinting? 
Related:  https://engineering.salesforce.com/tls-fingerprinting-with-ja3-and-ja3s-247362855967

**Comment by erebe** [comment]
done in pre-release 3.1 
https://github.com/erebe/wstunnel/releases/tag/v3.1
