### ISSUE TITLE
Support or prebuilt binary for armv6l architecture?

### ISSUE THREAD

**Issue by minutmorph** [erebe/wstunnel#63]
Hello!

I'm quite new to all of this so I may be asking about something that is not actually an issue. I saw there is already a prebuilt binary for armv7l which will support most Raspberry Pis. I am using the Pi Zero which has armv6l architecture. I tried to build from source as suggested in the readme and received this error:

```
root@raspberrypi:~# curl -sSL https://get.haskellstack.org/ | sh
Detected Linux distribution: raspbian

Sorry, currently only 64-bit (x86_64) Linux binary is available.
```

Any help that you can provide will be appreciated!

Thank you very much

**Comment by erebe** [comment]
you can use stzck 2.1.3 which is the latest that support this architecture i think.

Take a look at this script to build it on ARM
https://github.com/erebe/wstunnel/blob/master/build_raspbian.sh
