### ISSUE TITLE
Website access issues

### ISSUE THREAD

**Issue by Saterlite** [erebe/wstunnel#66]
Heyo. I have an issue where I cannot access duckduckgo.com or speedtest.net when using wireguard and tunneling through wstunnel.

I thought the issue was with wstunnel itself, but I've tried to use [udp2raw](https://github.com/wangyu-/udp2raw-tunnel) with [udpspeeder](https://github.com/wangyu-/UDPspeeder) to tunnel wireguard and got the same issue, so I suppose it has something to do the way duckduckgo.com & speedtest.net deal with udp packets? Or something? I'm not sure and I don't know where to start debugging such an issue as I don't think it's possible (or I likely just do not know how) to view packet traffic going through wireguard and wstunnel.
Wireguard without any tunneling does fine and all websites can be accessed normally.

### Here is my server config:
**Wireguard:**
```
[Interface]
PrivateKey = <privkey>
Address = 10.6.0.1/24
ListenPort = 51820

[Peer]
PublicKey = <pubkey>
PresharedKey = <presharedkey>
AllowedIPs = 10.6.0.2/32
```
**wstunnel:**
```
wstunnel -v --server ws://0.0.0.0:8085 --restrictTo 127.0.0.1:51820
```

### Here is my client config:
**Wireguard:**
```
[Interface]
PrivateKey = <privkey>
Address = 10.6.0.2/24
DNS = 1.1.1.1, 1.0.0.1

[Peer]
PublicKey = <pubkey>
PresharedKey = <presharedkey>
Endpoint = 127.0.0.1:51820
AllowedIPs = 0.0.0.0/0
```
**wstunnel:**
```
wstunnel -v --udp --udpTimeoutSec -1 -L 127.0.0.1:51820:127.0.0.1:51820 ws://server:8085
```

My server is raspberry pi 4 5.4.79-v7l+.
My client is regular desktop, AMD cpu, 64 bit.

Speed between client and server was ~80Mbps, tested using Fast.com as that worked.

I'd be grateful of any help.

**Comment by erebe** [comment]
First try to ping your server with its VPN ip from your local machine. In your case `ping   10.6.0.1` from your raspberry.
If your ping respond, it means your VPN setup is correct. If it is not the case something is missing.

Second, wireguard is a point to point VPN, meaning that by default you cannot reach a machine outside your VPN network (in your case 10.6.0.0/24).
If you want your client to be able to reach duckduck.go throught your server with the VPN, you need to enable traffic forwarding and iptables masquerade for it to works.
See
* https://github.com/erebe/personal-server/blob/master/wireguard/wg0.conf#L5
* https://www.ducea.com/2006/08/01/how-to-enable-ip-forwarding-in-linux/
