### ISSUE TITLE
Service Name: Just "443" does not exist (name does not resolve)

### ISSUE THREAD

**Issue by nashford77** [erebe/wstunnel#68]
./wstunnel -v --server wss://0.0.0.0/ --restrictTo 127.0.0.1:XXXXX

Starting server with opts WsServerInfo {useTls = True, host = "0.0.0.0/", port = 443}

WAIT for TLS connection on 0.0.0.0/:443

wstunnel: Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_PASSIVE], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "0.0.0.0/", service name: Just "443"): does not exist (Name does not resolve)

**Comment by nashford77** [comment]
I assume perhaps, the syntax is: wss://0.0.0.0:443 then instead?

Is there a way to run this in the background by the way so that it doesn't sit waiting on the CLI ?

**Comment by erebe** [comment]
It is due to the last trailing / of `wss://0.0.0.0/`, just remove it.
For running wstunnel in background, just start it via a systemd service, or some in docker container
