### ISSUE TITLE
Enable custom TLS certificate

### ISSUE THREAD

**Issue by c1b3rd0rk** [erebe/wstunnel#69]
Currently the server keys are embedded into the final release. Would it be possible to instead use certificates supplied by a command line option?  Something like: --server-key=server.key and --server-cert=server.crt
In that way you get a bit more security when using self signed certs or you could use officially signed certs.
You could the also supply the certificate on the client side and use it as additional authentication step

**Comment by erebe** [comment]
Hello,
I often wanted to add it, but basically always stepped down from doing it due to TLS having many knobs to turn.
I usually recommend people that want a custom TLS certificate to put in front a reverse proxy (like nginx) to allow them the certificate they want and configure everything fully.

You can take an example of this configuration for nginx, https://www.npmjs.com/package/wstunnel#ssl-setup
or https://github.com/erebe/personal-server/blob/master/app/wstunnel.yml if you want kubernetes

**Comment by c1b3rd0rk** [comment]
Tried it with nginx and it works :) But wstunnel does not seem to complain about self-signed certs. It automatically accepts those as valid.  Is there some way to make the client verify it connected to the right server? Stunnel for example has the option to supply the server cert to the *client* config so you kind of pin the certificate and know if something is wrong. In that way you can also use self-signed certificates without any errors showing up.

**Comment by erebe** [comment]
Perfect.
For the self-signed certificate, the client automatically accept any certificate even if they are not valid.
If you want to kind of pin between client and server, you can use the
```
 --upgradePathPrefix=String             Use a specific prefix that will
                                            show up in the http path in the
                                            upgrade request. Useful if you need
                                            to route requests server side but
                                            don't have vhosts
```

and only proxy pass in nginx this special location.
You can take reference from this issue https://github.com/erebe/wstunnel/issues/14

It will allow client and server to share a specific secret, and only people using this specific upgradePrefixPath with wstunnel will be allowed to connect to your proxy.

So far I don't plan to add the command line flag to allow/disallow unverified certificate, as the purpose of wstunnel is only to allow your traffic to pass through, not to protect the security of the data you transmit
