### ISSUE TITLE
Windows Connecting to ARMV71 - Error ?

### ISSUE THREAD

**Issue by nashford77** [erebe/wstunnel#70]
Hello - the FW port is open before anyone asks on the other end :) If you telnet it responds.

C:\temp\wstunnel>wstunnel -v --udp --udpTimeoutSec -1 -L 127.0.0.1:xyz:127.0.0.1:xyz wss://mysite.com:443
WAIT for datagrames on 127.0.0.1:xyz
DEBUG :: Oppening tcp connection to mysite.com:443
ERROR :: Cannot establish the connection to the server
DEBUG :: ====
user error (Network.Socket.gai_strerror not supported: 11001)
====
DEBUG :: TIMEOUT connection

 ??? What does this mean :)

**Comment by nashford77** [comment]
I used just the IP vs the name (seems it does not do a lookup?)

WAIT for datagrames on 127.0.0.1:xyz
DEBUG :: Oppening tcp connection to my-ip:443
DEBUG :: TIMEOUT connection

telnetting to 443 (where the server it) on this same IP works just fine - is NOT a FW issue.

**Comment by nashford77** [comment]
I am putting wireguard across it - perhaps thats the issue?

2020-12-27 14:41:43.190: [TUN] [MY-TUN] peer(.......) - Failed to send handshake initiation write udp4 0.0.0.0:xyz->127.0.0.1:xyz: wsasendto: The requested address is not valid in its context

maybe this is the root - i should be able to point WG to localhost i assume without issue on the port i choose?

**Comment by nashford77** [comment]
I see sometimes on the server side the following ? 

wstunnel: HandshakeFailed Error_EOF
wstunnel: HandshakeFailed Error_EOF
wstunnel: HandshakeFailed (Error_Protocol ("no cipher in common with the client",True,HandshakeFailure))
wstunnel: HandshakeFailed Error_EOF
wstunnel: HandshakeFailed Error_EOF
wstunnel: HandshakeFailed Error_EOF
wstunnel: HandshakeFailed Error_EOF
wstunnel: HandshakeFailed Error_EOF
wstunnel: HandshakeFailed (Error_Protocol ("no cipher in common with the client",True,HandshakeFailure))
wstunnel: HandshakeFailed Error_EOF

**Comment by nashford77** [comment]
I tried with windows to say bind to 0.0.0.0 vs 127.0.0.1 - windows seems to not like this ? either way nothing will connect the ARMV71 version and the Windows one.... ?

**Comment by erebe** [comment]
Can you describe more rigorously your setup please? 
Like:
* wstunnel version and arch for each computer
* The command you used to start wstunnel on both end
* Test with a simple dns request if you use UDP

From your log server 
```
no cipher in common with the client
```
The error arise with TLS handshaking, where client and server have to pick a cipher suite in common to encrypt the communication. For unknown reason the client and server does not have any in common.
If it is actually the case, a tcpdump on the server side should be mandatory to make any progress
