### ISSUE TITLE
Windows 10 + Coporate http proxy --> Cannot do tls handshake with the server 

### ISSUE THREAD

**Issue by SadarSSI** [erebe/wstunnel#71]
Hello,

I have the following error in client
ERROR :: Cannot do tls handshake with the server
DEBUG :: ====
HandshakeFailed (Error_Packet_Parsing "Failed reading: invalid header type: 72 \ nFrom: \ theader \ n \ n")

and this error from server side 
wstunnel: HandshakeFailed (Error_Misc "user error (unexpected type received. expecting handshake and got: Alert [(AlertLevel_Fatal,CertificateUnknown)])")

server side: updated archlinux, wstunnel 3.0-2 (installed via yay from aur/wstunnel)
client side: windows 10, wstunnel downloaded from https://github.com/erebe/wstunnel/releases/tag/v3.0

Server side command :
sudo wstunnel --verbose --server wss: //0.0.0.0: 443 -r localhost: 10020

Client side command :
wstunnel --verbose -L 9999: localhost: 10020 --httpProxy = myusername @ mydomain: mypasswd @ corporate_proxy: 3129 wss: //myserver.com: 443

I think the coporate proxy is an Olfeo SQuid which checks the TLS negotiation

However, if I bypass the coporate proxy via a linux proxy (privoxy) without user / passwd or TLS control, it works!

Any idea ?

**Comment by erebe** [comment]
Like that no.
If you have this error message 
```
ERROR :: Cannot do tls handshake with the server
```
It means that at least the negotiation with the proxy have been done, somehow.
But if you remove it from the equation and it works, it means that it is the culprit.

Do you know if the proxy is using HTTP or HTTPS protocol ?

To investigate further can you do a tcpdump and send me some PCAP of the client/server network exchange ?
(You can send them to my email address)

**Comment by SadarSSI** [comment]
OK, I just found what was wrong ; - //

It was the way to declare the domain name, the user and the password, the correct definition in my case is
DOMAIN \ user: passwd
user @ domain: passwd does not work with an Olfeo Squid!

A suggestion / question if you will allow me:
On the server side, is there a way to dynamically redirect to a hostname something like:
sudo wstunnel --verbose --server wss: //0.0.0.0: 443 -r % h:% p
Indeed, I use wstunnel to do ssh and I would like to avoid making a jump host to the destination.

Do you think this is possible?

In any case, thank you for your software!

**Comment by erebe** [comment]
haha glad to see that the issue is not in the code.

For your question, you can use ssh proxy command on the client side to avoid having to do a hop on the server first.
https://github.com/erebe/wstunnel#as-proxy-command-for-ssh
SSH is going to spawn a wstunnel client and proxy the connection through it with that.

Regarding server side, no it is not possible to parametrize the -r as it will be kind of break its purpose of limiting proxy usage.
