### ISSUE TITLE
add dns for resolving websocket address

### ISSUE THREAD

**Issue by mokhtarabadi** [erebe/wstunnel#72]
first thanks for your great project, I used (wstunnel + tun2socks + trojan + pdnsd) to create a VPN and redirect all system traffic through that, but I think if the wstunnel can use a DNS server for resolving the WebSocket address which I give the wstunnel to connect will be a good idea, and if you doing that I can remove pdnsd 

now I configured pdnsd to resolve WebSocket address by the first DNS server (for example 1.1.1.1) and others by the second DNS server (for example 8.8.8.8)
and I route the first DNS server directly to avoid DNS errors while resolving the WebSocket address

mean of WebSocket address is the domain name wstunnel client used to connect to for example wss://example.org

**Comment by erebe** [comment]
Hello,
This is not likely to happen. It is up to the client to resolve correctly dns, and if they can't (why ?) either use directly the ip address of the server.

**Comment by mokhtarabadi** [comment]
hello, for now, I can use pre-release build and set sni and host header, everything works great
