### ISSUE TITLE
feature request: Reverse tunneling

### ISSUE THREAD

**Issue by bananabr** [erebe/wstunnel#73]
Hi,

I would be really interested in implementing the reverse tunneling feature. Could you provide me with some minimal guidance? What are the major difficulties you have mapped so far, how would the high-level object's interaction look like, etc?

Cheers,

**Comment by erebe** [comment]
Should not be hard to add, but it has never been requested more than once.
and as you can already do it in a wonky way https://github.com/erebe/wstunnel/issues/19
I never spent time on this feature.

P.s: I am starting a new job, so i doubt i will implement it in the near future

Hope it helps

**Comment by cmprmsd** [comment]
This would be a great addition for wstunnel :)
Maybe someone wants to start a pull request!

**Comment by erebe** [comment]
It is done in release https://github.com/erebe/wstunnel/releases/tag/v8.0.0 
Let me know if it is nok for you
