### ISSUE TITLE
Low speed on raspberrypi

### ISSUE THREAD

**Issue by D4rkTT** [erebe/wstunnel#75]
Hello, i wanna to say good job
I tried it on windows with DigitalOcean vps and working fine with speed ~= 25 Mbps
But on raspberrypi 3b with same vps it being so low speed ~= 3 Mbps

Any idea?

**Comment by erebe** [comment]
You are maybe CPU bound ?
Try to run a `dstat -lnvrp` on the machine while wstunnel is running to get more insight
