### ISSUE TITLE
nginx reverse proxy authentication issue

### ISSUE THREAD

**Issue by HamedSepehr** [erebe/wstunnel#76]
I needed some kind of authentication and found out you suggesting using nginx reverse proxy to authenticate user on #12 I created nginx reverse proxy and every thing works fine. Here is the configuration I used for reverse proxy (I have wstunnel running on server on port 8080):

```
location / {
proxy_pass http://127.0.0.1:8080;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
}
```

But the issue shows up when I add authentication to nginx, after adding authentication I run wstunnel on the client this way:
```
wstunnel -D 8888 ws://user:pass@server_address:80
```
and then I get this error message:
```
wstunnel: Invalid port number `pass@server_address:80`
CallStack (from HasCallStack):
  error, called at app/Main.hs:87:31 in main:Main
```

How should I give wstunnel the user and pass that's needed to authenticate?

PS: Is it possible for you to add some kind of authentication like this?
```
wstunnel --server --password="SuperSecurePassword" ws://0.0.0.0:8080
wstunnel -D 8888 --password="SuperSecurePassword" ws://server_address:8080
```

**Comment by erebe** [comment]
Hello,

You need to use --prefixPath like in https://github.com/erebe/wstunnel/issues/14 in order to authenticate
Basically it is a shared secret between you and your server

**Comment by HamedSepehr** [comment]
Thanks for the response, I can do #14 in my environment, but I still believe having some king of authentication on wstunnel itself is useful.

**Comment by contrun** [comment]
See also https://github.com/erebe/wstunnel/issues/50. https://github.com/erebe/wstunnel/issues/50 discussed on the client side support for basic auth.

**Comment by erebe** [comment]
Added support in version 4.1
