### ISSUE TITLE
Connection closed by client

### ISSUE THREAD

**Issue by AmandaJonesAway** [erebe/wstunnel#78]
I have noticed that when the application connected to the client is closed, the tunnel would appear not to be closed and the final server does not know that the client has gone.  Data is still accepted from the server and it is only when the server application times out that the connection is closed.   The reverse is not true; if the server closes the connection, then this seems to shut down everything fine, and the client's application reports the connection closed.

**Comment by erebe** [comment]
Hello thanks for reporting,
Can you describe precisely the setup so that I can try to reproduce it on my side ?

**Comment by AmandaJonesAway** [comment]
Apologies for the delay; I was trying to set up a local implementation to test in isolation ...

It seems there is a ~20 second delay before a connection closed from shutting down the client application is reflected through to the server on the local connection (same LAN) (client -> windows wstunnel.exe -> apache -> wstunnel-linux -> server.)

However on my production system, it is in excess of 90 seconds (this is the point where the server times out) however this is a lot more round the houses (client -> windows wstunnel.exe -> public caching proxy -> 3rd party host -> redir -> ssh tunnel -> apache -> wstunnel-linux -> server.) 

On that basis, I'll have to see what optimisations I can do, as something else is clearly keeping it open beyond what wstunnel is doing; sorry to have troubled you!

**Comment by erebe** [comment]
Hello,
That indeed an impressive setup that you have :rofl: 
If you manage to find out more information regarding the issue, feel free to re-open the issue
