### ISSUE TITLE
armv7l binary

### ISSUE THREAD

**Issue by mghadam** [erebe/wstunnel#81]
Could you also provide armv7l binary in your releases? Im using wstunnel in raspberry pi and no armv7l binary is available for v4 yet.

**Comment by mghadam** [comment]
Here is the binary I compiled on `armv7l` using [this guide](https://github.com/erebe/wstunnel/blob/master/build_raspbian.sh). 

[wstunnel-armv7l.zip](https://github.com/erebe/wstunnel/files/6632511/wstunnel-armv7l.zip)

**Comment by erebe** [comment]
Thank you, going to add it :)

**Comment by erebe** [comment]
https://github.com/erebe/wstunnel/releases/download/v4.0/wstunnel-armv7l-linux.zip
