### ISSUE TITLE
ARMv7 support

### ISSUE THREAD

**Issue by cblims** [erebe/wstunnel#9]
Hi, is it possible for you to publish a binary for ARMv7 (Raspberry PI)

I've tried to compile myself, but there seems to be some problems downloading indexes and GHC version for ARM.

**Comment by erebe** [comment]
I will give it a shot this weekend.
It will give me an occassion to use my rasberrypi which is taking dust

**Comment by erebe** [comment]
my sd card reader is dead, I am waiting to receive a new one

**Comment by erebe** [comment]
Can you try out this binary https://github.com/erebe/wstunnel/releases/download/1.2/wstunnel-armhf and tell me if it is working for you ?

The binary is a bit fat as I can't trim some code out due to this feature being un-supported on ARM

**Comment by cblims** [comment]
Nice, it starts. Give me a couple of days, and I will test it against a server as well. As they say, size doesn't matter... ;) Thanks!

**Comment by erebe** [comment]
re-open if not working
