### ISSUE TITLE
--version does not show the version

### ISSUE THREAD

**Issue by streaps** [erebe/wstunnel#90]
`wstunnel --version` does not really "print version information"

```
$ /srv/wstunnel/wstunnel --version
Use the websockets protocol to tunnel {TCP,UDP} traffic
wsTunnelClient <---> wsTunnelServer <---> RemoteHost
Use secure connection (wss://) to bypass proxies
```

**Comment by erebe** [comment]
Putting it in the backlog, I never implemented this command
Thanks for reporting :)

**Comment by erebe** [comment]
fixed in https://github.com/erebe/wstunnel/releases/tag/v6.0
