### ISSUE TITLE
SSH connections hanging consistently after large data throughput

### ISSUE THREAD

**Issue by jenic** [erebe/wstunnel#94]
## Premise

Trying to obfuscate WireGuard traffic to egress restrictive networks with deep packet inspection from an Intel NUC device.

## Setup

Loosely following [guide linked in the readme](https://kirill888.github.io/notes/wireguard-via-websocket/). An Intel NUC running Arch Linux is configured to establish a wireguard connection using wstunnel to an Ubuntu 20.04 AWS EC2 instance running nginx/wstunnel/wireguard. I connect from a third machine (Arch Linux) to the NUC using `ssh -J aws-system nuc-wg-ip` to SSH hop from the AWS system into the NUC through WireGuard. 

## Problem Symptoms

Doing commands with high data speed (not necessarily large, just fast) will irrevocably hang SSH session and it must be hard closed. New sessions can be created but they will also quickly hang as well if repeating any problem commands. Commands such as `pacman -Syu` or `journalctl --since=today` and scrolling through the output quickly will cause the session to hang and never return.

CPU and RAM look fine on both ends of the tunnel (AWS & NUC) and I don't see anything of note in WireGuard debug output, WSTunnel output (using `-v` on both ends), or anywhere else I can think of.

---

Have you encountered a problem such as this? Am I doing something terribly wrong? Also just want to say: this is a really cool tool, thanks for making it!

**Comment by erebe** [comment]
Hello,

Can you let me know how you start wstunnel client and server ?
Besides that, without any extra information, I can't tell you much what is happening.
You can try doing some tcpdump at the server and client location in order to see why the stream stall.
Also try to start ssh with the option `-vvv` you may will have some information also

**Comment by erebe** [comment]
did you find your issue ?

**Comment by jenic** [comment]
No I switched to stunnel+openvpn :( thanks for the help though!
