### ISSUE TITLE
Feature request: configuration file

### ISSUE THREAD

**Issue by mo-rijndael** [erebe/wstunnel#95]
Storing configuration in file is useful, when tunnels are static (common case I think). Also it will be good for packaging - user can define tunnels in separate file, and start package-provided service (systemd unit, for example).
There can be CLI option like `--config=<path>` for that

**Comment by erebe** [comment]
Sadly i doubt i will implement this feature due to lack of time to invest in this project :(

**Comment by mikahe** [comment]
Config file or/and command line option for using custom certificate would also be nice

**Comment by cattyhouse** [comment]
in case using systemd, you can add `EnvironmentFile=` as a simple config file, and start wstunnel with `--parameters $var1 --parameters $var2 ...` where `$var1 $var2 ...` is defined in the file assigned by `EnvironmentFile=`
