### ISSUE TITLE
why wstunnel take up huge virtual memory

### ISSUE THREAD

**Issue by qluo1** [erebe/wstunnel#97]
running wstunnel on ubuntu 20.01/pi4 found each wstunnel process took 270G virtual memory? 

the residual not too bad max 44K.

Linux pi4 5.11.0-1019-raspi #20-Ubuntu SMP PREEMPT Tue Sep 21 15:23:42 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

pi4:~/works$ ps -eo pid,tid,class,rtprio,stat,vsz,rss,comm | grep wstunnel 
   268182  268182 TS       - Sl   269435092 19020 wstunnel                               
2284813 2284813 TS       - Sl   269730260 34264 wstunnel                               
2296457 2296457 TS       - Sl   269730260 44336 wstunnel                               
2476984 2476984 TS       - Sl   269582676 24436 wstunnel                               

using 3.0 binary version download from the site

**Comment by marty-macfly** [comment]
It's an Haskell behavior more than a wstunnel one,you can see https://gitlab.haskell.org/ghc/ghc/-/issues/14193, you can change that by defining RTS settings http://ghc.gitlab.haskell.org/ghc/doc/users_guide/runtime_control.html for example if you add that on wstunnel command line `wstunnel +RTS -M100m -RTS` it will limit memory usage of wstunnel.

**Comment by qluo1** [comment]
thanks for the response, tried +RTS -M100m -RTS, make no difference. 

nevertheless will close the item
