### ISSUE TITLE
Completely custom headers

### ISSUE THREAD

**Issue by TomFahey** [erebe/wstunnel#98]
First of all, I'd like to say this project is absolutely brilliant and has amazing potential, so thank you for taking the time to both author and share it for us to use!

Now, with that said, I think an additional feature which would offer a great deal of utility is the ability to provide a list of custom headers when calling the client, which could be provided as part of the websockets tunnel? My own interest in this would be for use with Cloudflare's Access service, which provides the ability for requests sent to applications behind Access to be checked for  `CF-Access-Client-ID: <Client ID>` and `CF-Access-Client-Secret: <Client Secret>` headers, which when matched, will allow the request to be forwarded and a JWT scoped to that client ID to be generated ([link](https://developers.cloudflare.com/cloudflare-one/identity/service-auth/service-tokens)).

I think this would be a great option for authentication, as it would allow it to be tied into existing infrastructure, much like using Nginx as proxy.

I know nothing of Haskell, but a quick search through the source files threw up line 66 in Tunnel.hs.

Would it be as simple as adding appending an extra two dictionary values to `TunnelSettings` in Types.hs, and then essentially adding similar checks for these in Tunnel.hs?

**Comment by erebe** [comment]
I can add that, will take a look at it when I will have some free time to do that :)

**Comment by erebe** [comment]
I can add that, will take a look at it when I will have some free time to do that :)

**Comment by erebe** [comment]
Done in latest release https://github.com/erebe/wstunnel/releases/tag/v4.1
command line flag is -H

Enjoy :)

**Comment by TomFahey** [comment]
Thank you so much!
